-- =====================================================================
-- VELTRIX HOM — migration-008
-- Durable request model, atomic claim/completion, leased processing jobs,
-- per-page source model, and explicit printed-page mapping.
--
-- Additive + idempotent. Run AFTER migration-007. No table is dropped and
-- no existing row is destroyed, so this is safe on the live database.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. DURABLE CHAT REQUESTS
--
-- V7 keyed idempotency on (chat_id, client_message_id). That cannot stop
-- two concurrent NEW-chat submits, because neither has a chat_id yet — so
-- both created a chat, both inserted a user message, and both called
-- Gemini. The unit of idempotency has to exist BEFORE the chat does, and
-- be unique per user rather than per chat.
-- ---------------------------------------------------------------------
create table if not exists public.chat_requests (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references public.profiles on delete cascade,
  -- Generated by the client before the first attempt and reused by every
  -- retry of the same logical message.
  client_request_id   uuid not null,
  chat_id             uuid references public.chats on delete cascade,
  user_message_id     uuid references public.messages on delete set null,
  assistant_message_id uuid references public.messages on delete set null,
  status              text not null default 'claimed'
                        check (status in ('claimed','processing','completed','failed','cancelled','uncertain')),
  -- Only the holder of the current lease may advance the request.
  lease_token         uuid,
  lease_expires_at    timestamptz,
  -- Set immediately before the Gemini call. Its presence is what makes a
  -- crashed request "uncertain" rather than safely retryable.
  provider_started_at timestamptz,
  attempt_count       int not null default 0,
  response_snapshot   jsonb,
  error_code          text,
  error_message       text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  completed_at        timestamptz
);

-- The global idempotency key. Deliberately NOT scoped to chat_id.
create unique index if not exists chat_requests_user_client_uniq
  on public.chat_requests (user_id, client_request_id);

create index if not exists chat_requests_status_idx
  on public.chat_requests (status, lease_expires_at);
create index if not exists chat_requests_chat_idx
  on public.chat_requests (chat_id, created_at desc);

-- ---------------------------------------------------------------------
-- 2. EXPLICIT MESSAGE ↔ REQUEST RELATION
--
-- V7 found the reply by taking the first assistant message created after
-- the user message. That is a guess: a concurrent request, a clock skew,
-- or an out-of-order insert breaks it. An explicit foreign key plus a
-- partial unique index makes "one user message and one assistant message
-- per request" a database guarantee instead of a convention.
-- ---------------------------------------------------------------------
alter table public.messages add column if not exists request_id uuid
  references public.chat_requests on delete set null;

create unique index if not exists messages_request_user_uniq
  on public.messages (request_id) where request_id is not null and role = 'user';
create unique index if not exists messages_request_assistant_uniq
  on public.messages (request_id) where request_id is not null and role = 'assistant';
create index if not exists messages_request_idx
  on public.messages (request_id);

-- Composite pagination cursor. Timestamp alone can skip or duplicate rows
-- that share a created_at value.
create index if not exists messages_chat_created_id_idx
  on public.messages (chat_id, created_at desc, id desc);

-- ---------------------------------------------------------------------
-- 3. ATOMIC CLAIM
--
-- Serialises concurrent submits of the same logical message through a
-- transaction-scoped advisory lock derived from (user_id, client_request_id).
-- The lock is released automatically at COMMIT/ROLLBACK, so a crashed
-- backend cannot leave it held.
--
-- Returns exactly one row describing what the caller should do:
--   claimed          → you own it, go call the model
--   processing       → someone else owns it, poll
--   completed        → replay p_response_snapshot, do NOT call the model
--   failed           → safe to retry (provider never started)
--   uncertain        → provider may have run; requires explicit user retry
-- ---------------------------------------------------------------------
create or replace function public.claim_chat_request(
  p_user_id           uuid,
  p_client_request_id uuid,
  p_chat_id           uuid,
  p_text              text,
  p_attachments       jsonb default null,
  p_title             text default null,
  p_talent_id         uuid default null,
  p_lease_seconds     int default 180
)
returns table (
  outcome           text,
  request_id        uuid,
  chat_id           uuid,
  user_message_id   uuid,
  lease_token       uuid,
  response_snapshot jsonb,
  status            text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_req      public.chat_requests;
  v_chat_id  uuid := p_chat_id;
  v_lease    uuid;
  v_user_msg uuid;
begin
  -- One writer at a time for this exact logical request. hashtextextended
  -- gives a stable 64-bit key from the two identifiers.
  perform pg_advisory_xact_lock(
    hashtextextended(p_user_id::text || ':' || p_client_request_id::text, 0)
  );

  select * into v_req
    from public.chat_requests
   where user_id = p_user_id and client_request_id = p_client_request_id;

  if found then
    -- Already finished: hand back the stored answer, never re-invoke.
    if v_req.status = 'completed' then
      return query select 'completed'::text, v_req.id, v_req.chat_id,
                          v_req.user_message_id, null::uuid,
                          v_req.response_snapshot, v_req.status;
      return;
    end if;

    -- A live owner exists.
    if v_req.status in ('claimed','processing')
       and v_req.lease_expires_at is not null
       and v_req.lease_expires_at > now() then
      return query select 'processing'::text, v_req.id, v_req.chat_id,
                          v_req.user_message_id, null::uuid,
                          null::jsonb, v_req.status;
      return;
    end if;

    -- Lease expired. If the provider had already been called we cannot
    -- know whether it ran, so we refuse to silently call it again.
    if v_req.provider_started_at is not null and v_req.status <> 'failed' then
      update public.chat_requests
         set status = 'uncertain', updated_at = now()
       where id = v_req.id;
      return query select 'uncertain'::text, v_req.id, v_req.chat_id,
                          v_req.user_message_id, null::uuid,
                          null::jsonb, 'uncertain'::text;
      return;
    end if;

    -- Never reached the provider: safe to take ownership again.
    v_lease := gen_random_uuid();
    update public.chat_requests
       set status = 'claimed',
           lease_token = v_lease,
           lease_expires_at = now() + make_interval(secs => p_lease_seconds),
           attempt_count = v_req.attempt_count + 1,
           updated_at = now()
     where id = v_req.id;

    return query select 'claimed'::text, v_req.id, v_req.chat_id,
                        v_req.user_message_id, v_lease, null::jsonb, 'claimed'::text;
    return;
  end if;

  -- First time we have seen this request.
  v_lease := gen_random_uuid();

  -- Create the chat exactly once, inside the same lock, so a concurrent
  -- duplicate submit cannot produce a second chat.
  if v_chat_id is null then
    insert into public.chats (user_id, title, skill_id)
    values (p_user_id, coalesce(nullif(btrim(p_title), ''), 'Yangi suhbat'), p_talent_id)
    returning id into v_chat_id;
  else
    -- Ownership check: never let a caller attach to someone else's chat.
    if not exists (select 1 from public.chats
                    where id = v_chat_id and user_id = p_user_id) then
      raise exception 'chat_not_found_or_forbidden' using errcode = '42501';
    end if;
  end if;

  insert into public.chat_requests (
    user_id, client_request_id, chat_id, status,
    lease_token, lease_expires_at, attempt_count
  ) values (
    p_user_id, p_client_request_id, v_chat_id, 'claimed',
    v_lease, now() + make_interval(secs => p_lease_seconds), 1
  ) returning * into v_req;

  insert into public.messages (
    chat_id, user_id, role, content, attachments, status, request_id, client_message_id
  ) values (
    v_chat_id, p_user_id, 'user', p_text, p_attachments, 'completed',
    v_req.id, p_client_request_id::text
  ) returning id into v_user_msg;

  update public.chat_requests
     set user_message_id = v_user_msg, updated_at = now()
   where id = v_req.id;

  return query select 'claimed'::text, v_req.id, v_chat_id, v_user_msg,
                      v_lease, null::jsonb, 'claimed'::text;
end;
$$;

-- ---------------------------------------------------------------------
-- 4. ATOMIC COMPLETION
--
-- Verifies the lease still belongs to the caller, then writes the
-- assistant message, the snapshot, and the terminal status in ONE
-- transaction. A stale owner whose lease expired cannot overwrite a
-- result that someone else already stored.
-- ---------------------------------------------------------------------
create or replace function public.complete_chat_request(
  p_user_id      uuid,
  p_request_id   uuid,
  p_lease_token  uuid,
  p_blocks       jsonb,
  p_snapshot     jsonb,
  p_subject      text default null,
  p_source_mode  text default null,
  p_model_used   text default null,
  p_latency_ms   int default null
)
returns table (assistant_message_id uuid, outcome text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_req public.chat_requests;
  v_msg uuid;
begin
  select * into v_req
    from public.chat_requests
   where id = p_request_id and user_id = p_user_id
   for update;

  if not found then
    raise exception 'request_not_found' using errcode = 'P0002';
  end if;

  -- Someone already completed it (e.g. a duplicate that won the race).
  if v_req.status = 'completed' then
    return query select v_req.assistant_message_id, 'already_completed'::text;
    return;
  end if;

  if v_req.lease_token is distinct from p_lease_token then
    raise exception 'stale_lease' using errcode = '55000';
  end if;

  insert into public.messages (
    chat_id, user_id, role, blocks, detected_subject, source_mode,
    model_used, latency_ms, status, request_id
  ) values (
    v_req.chat_id, p_user_id, 'assistant', p_blocks, p_subject, p_source_mode,
    p_model_used, p_latency_ms, 'completed', v_req.id
  )
  -- The partial unique index guarantees one assistant row per request; if
  -- it already exists we simply reuse it rather than failing the caller.
  on conflict (request_id) where request_id is not null and role = 'assistant'
  do update set blocks = excluded.blocks
  returning id into v_msg;

  update public.chat_requests
     set status = 'completed',
         assistant_message_id = v_msg,
         response_snapshot = p_snapshot,
         lease_token = null,
         lease_expires_at = null,
         completed_at = now(),
         updated_at = now()
   where id = v_req.id;

  update public.chats set updated_at = now() where id = v_req.chat_id;

  return query select v_msg, 'completed'::text;
end;
$$;

-- Marks the provider call as started; used to decide uncertain-vs-retryable.
create or replace function public.mark_request_provider_started(
  p_user_id uuid, p_request_id uuid, p_lease_token uuid, p_lease_seconds int default 180
) returns boolean
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  update public.chat_requests
     set provider_started_at = coalesce(provider_started_at, now()),
         status = 'processing',
         lease_expires_at = now() + make_interval(secs => p_lease_seconds),
         updated_at = now()
   where id = p_request_id and user_id = p_user_id and lease_token = p_lease_token;
  return found;
end; $$;

create or replace function public.fail_chat_request(
  p_user_id uuid, p_request_id uuid, p_lease_token uuid,
  p_error_code text, p_error_message text
) returns boolean
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  update public.chat_requests
     set status = case when provider_started_at is not null then 'uncertain' else 'failed' end,
         error_code = p_error_code, error_message = left(p_error_message, 500),
         lease_token = null, lease_expires_at = null, updated_at = now()
   where id = p_request_id and user_id = p_user_id and lease_token = p_lease_token;
  return found;
end; $$;

-- Only the trusted backend (service role) may execute these. The browser
-- must never be able to claim or complete a request directly.
revoke all on function public.claim_chat_request(uuid,uuid,uuid,text,jsonb,text,uuid,int) from public, anon, authenticated;
revoke all on function public.complete_chat_request(uuid,uuid,uuid,jsonb,jsonb,text,text,text,int) from public, anon, authenticated;
revoke all on function public.mark_request_provider_started(uuid,uuid,uuid,int) from public, anon, authenticated;
revoke all on function public.fail_chat_request(uuid,uuid,uuid,text,text) from public, anon, authenticated;
grant execute on function public.claim_chat_request(uuid,uuid,uuid,text,jsonb,text,uuid,int) to service_role;
grant execute on function public.complete_chat_request(uuid,uuid,uuid,jsonb,jsonb,text,text,text,int) to service_role;
grant execute on function public.mark_request_provider_started(uuid,uuid,uuid,int) to service_role;
grant execute on function public.fail_chat_request(uuid,uuid,uuid,text,text) to service_role;

-- ---------------------------------------------------------------------
-- 5. DURABLE PROCESSING JOBS
--
-- V7 ran PDF work as `void processPdf(...)` after the HTTP response. On
-- Render's free tier the service sleeps and the filesystem is ephemeral,
-- so that work simply vanished with no way to resume. Jobs now live in
-- Postgres with a lease and a checkpoint.
-- ---------------------------------------------------------------------
create table if not exists public.processing_jobs (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references public.profiles on delete cascade,
  source_id       uuid not null references public.sources on delete cascade,
  job_type        text not null,     -- extract | classify | page_map | ocr_page | index
  stage           text,
  priority        int not null default 100,   -- lower runs first
  status          text not null default 'queued'
                    check (status in ('queued','running','completed','failed','paused_quota','cancelled')),
  checkpoint_page int not null default 0,
  total_pages     int,
  progress        int not null default 0,
  attempt_count   int not null default 0,
  lease_token     uuid,
  lease_expires_at timestamptz,
  heartbeat_at    timestamptz,
  error_code      text,
  error_message   text,
  next_retry_at   timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- At most one live job per (source, type): prevents a second worker or a
-- retried request from queueing duplicate work for the same book.
create unique index if not exists processing_jobs_active_uniq
  on public.processing_jobs (source_id, job_type)
  where status in ('queued','running','paused_quota');

create index if not exists processing_jobs_claim_idx
  on public.processing_jobs (status, priority, next_retry_at);

-- Atomically hands one runnable job to a worker. FOR UPDATE SKIP LOCKED
-- lets the web service and a future dedicated worker poll the same queue
-- without ever taking the same row.
create or replace function public.claim_processing_job(
  p_lease_seconds int default 120
)
returns public.processing_jobs
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_job public.processing_jobs; v_lease uuid := gen_random_uuid();
begin
  select * into v_job from public.processing_jobs
   where (status = 'queued' and (next_retry_at is null or next_retry_at <= now()))
      or (status = 'running' and lease_expires_at < now())  -- reclaim dead lease
   order by priority asc, created_at asc
   for update skip locked
   limit 1;

  if not found then return null; end if;

  update public.processing_jobs
     set status = 'running', lease_token = v_lease,
         lease_expires_at = now() + make_interval(secs => p_lease_seconds),
         heartbeat_at = now(), attempt_count = v_job.attempt_count + 1,
         updated_at = now()
   where id = v_job.id
   returning * into v_job;

  return v_job;
end; $$;

revoke all on function public.claim_processing_job(int) from public, anon, authenticated;
grant execute on function public.claim_processing_job(int) to service_role;

-- ---------------------------------------------------------------------
-- 6. PER-PAGE SOURCE MODEL
--
-- Every physical page gets a row, including blank and scanned ones, so
-- the system can answer "what is on PDF page 812" without re-deriving
-- page boundaries from a flat text blob.
-- ---------------------------------------------------------------------
alter table public.source_pages add column if not exists printed_page_label text;
alter table public.source_pages add column if not exists printed_page_confidence real;
alter table public.source_pages add column if not exists page_type text
  check (page_type in ('text','scanned','mixed','blank','failed'));
alter table public.source_pages add column if not exists ocr_text text;
alter table public.source_pages add column if not exists ocr_status text
  check (ocr_status in ('pending','running','done','failed','skipped'));
alter table public.source_pages add column if not exists ocr_confidence real;
alter table public.source_pages add column if not exists ocr_provider text;
alter table public.source_pages add column if not exists indexing_status text
  check (indexing_status in ('pending','chunked','embedded','failed','paused_quota'));
alter table public.source_pages add column if not exists content_checksum text;
alter table public.source_pages add column if not exists last_error text;
alter table public.source_pages add column if not exists updated_at timestamptz default now();

create index if not exists source_pages_ocr_status_idx
  on public.source_pages (source_id, ocr_status);
create index if not exists source_pages_type_idx
  on public.source_pages (source_id, page_type);

-- ---------------------------------------------------------------------
-- 7. PRINTED-PAGE MAPPING
--
-- A single global offset is wrong for real textbooks: Roman front matter,
-- inserts and appendices each shift numbering. Confirmed mappings are
-- stored individually and grouped into validated segments.
-- ---------------------------------------------------------------------
create table if not exists public.source_page_map (
  id              uuid primary key default gen_random_uuid(),
  source_id       uuid not null references public.sources on delete cascade,
  pdf_page_index  int not null,
  printed_label   text,
  printed_number  int,
  confidence      real not null default 0,
  verified_by     text not null default 'ocr'   -- ocr | user | inferred
    check (verified_by in ('ocr','user','inferred')),
  created_at      timestamptz not null default now(),
  unique (source_id, pdf_page_index)
);
create index if not exists source_page_map_printed_idx
  on public.source_page_map (source_id, printed_number);

-- Honest capability flags: a scanned book can be usable for exact-page
-- questions long before it is fully searchable.
alter table public.sources add column if not exists capability_exact_page boolean not null default false;
alter table public.sources add column if not exists capability_full_search boolean not null default false;
alter table public.sources add column if not exists indexed_pages int not null default 0;
alter table public.sources add column if not exists processing_stage text;

-- ---------------------------------------------------------------------
-- 8. RLS
-- Read access for the owner; all writes flow through the trusted backend.
-- ---------------------------------------------------------------------
alter table public.chat_requests enable row level security;
alter table public.processing_jobs enable row level security;
alter table public.source_page_map enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename='chat_requests' and policyname='chat_requests_own') then
    create policy chat_requests_own on public.chat_requests
      for select using (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where tablename='processing_jobs' and policyname='processing_jobs_own') then
    create policy processing_jobs_own on public.processing_jobs
      for select using (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where tablename='source_page_map' and policyname='source_page_map_own') then
    create policy source_page_map_own on public.source_page_map
      for select using (
        exists (select 1 from public.sources s
                 where s.id = source_page_map.source_id and s.user_id = auth.uid())
      );
  end if;
end $$;
