import { Router } from 'express'
import { z } from 'zod'
import { CACHE_THRESHOLD, MODELS } from '../config.js'
import { requireAuth } from '../middleware/auth.js'
import { admin } from '../services/supabase.js'
import { embedOne, generate, quotaPercent } from '../services/gemini.js'
import { parseSlashCommands, routeMessage, stripFences } from '../services/subjectRouter.js'
import { buildSystemPrompt, REFUSAL_BLOCKS } from '../prompts/system.js'
import { renderPageWindow, renderSkimSample } from '../services/pdfVision.js'
import { buildEvidence, validateEvidence, EVIDENCE_CONTRACT, INJECTION_GUARD, type EvidenceItem } from '../services/evidence.js'
import { resolveRenderCenter } from '../services/pageLocator.js'
import { prioritizePages } from '../services/ocr.js'
import { routeQuery, sourceCoverage } from '../services/tocRouter.js'
import { checkLimit } from '../services/limits.js'
import { normalizeBlocks } from '../services/answerNormalize.js'

/**
 * Keeps a chat request's lease alive while a long generation runs.  (V9)
 *
 * A Gemini answer can outlast the 180s request lease. Without renewal a
 * stale reclaim could mark the request `uncertain` while the first attempt
 * is still working. The heartbeat renews it every 60s and flips `lost` the
 * instant ownership is gone, so we never persist a result we no longer own.
 */
function startRequestHeartbeat(userId: string, requestId: string, leaseToken: string | null) {
  const state = { lost: false }
  if (!leaseToken) return { state, stop: () => {} }
  const timer = setInterval(async () => {
    try {
      const { data } = await admin.rpc('extend_chat_request_lease', {
        p_user_id: userId, p_request_id: requestId, p_lease_token: leaseToken, p_seconds: 180,
      })
      if (!data) state.lost = true
    } catch { /* transient; next beat retries */ }
  }, 60_000)
  if (typeof timer.unref === 'function') timer.unref()
  return { state, stop: () => clearInterval(timer) }
}

export const chatRouter = Router()

const Media = z.object({
  mimeType: z.string().min(3).max(120),
  data: z.string().min(1).max(30_000_000),
  name: z.string().max(240).optional(),
})
const Body = z.object({
  chatId: z.string().uuid().nullable().optional(),
  text: z.string().min(1).max(8000),
  lockedSourceId: z.string().uuid().nullable().optional(),
  lockedSourceIds: z.array(z.string().uuid()).max(8).optional(),
  image: Media.nullable().optional(), // legacy client compatibility
  media: Media.nullable().optional(),
  talentId: z.string().uuid().nullable().optional(),
  /** Stable id generated by the client before the first attempt. Makes a
   *  double-tap, a retry, or a refresh mid-request idempotent instead of
   *  inserting the same logical message twice. */
  clientMessageId: z.string().min(6).max(64).optional(),
  /** Stable UUID generated once per logical message and reused by every
   *  retry. This is the global idempotency key for the whole request. */
  clientRequestId: z.string().uuid().optional(),
})

interface Chunk {
  id?: string
  source_id: string
  source_title?: string
  page_number: number
  content: string
  heading?: string | null
}

chatRouter.post('/', requireAuth, async (req, res, next) => {
  const started = Date.now()
  // Populated once the claim succeeds so the catch block can mark the
  // durable request failed instead of leaving it stuck as 'processing'.
  let activeRequest: { userId: string; requestId: string; leaseToken: string | null } | null = null
  try {
    const userId = req.userId!
    const body = Body.parse(req.body)
    const slash = parseSlashCommands(body.text)
    const question = slash.cleanText || body.text
    const media = body.media ?? body.image ?? null

    const [{ data: profile }, { data: settings }] = await Promise.all([
      admin.from('profiles').select('grade,school_language').eq('id', userId).single(),
      admin.from('user_settings').select('*').eq('user_id', userId).single(),
    ])
    const answerLength = slash.answerLength ?? settings?.answer_length ?? 'normal'

    // ---- ATOMIC CLAIM -------------------------------------------------
    // Everything that must happen exactly once — create the chat, insert the
    // user message, take ownership of this logical request — happens inside
    // one advisory-locked transaction in the database. V7 did these as
    // separate statements, so two concurrent submits of the same message
    // could each create a chat and each call Gemini.
    const clientRequestId = body.clientRequestId ?? body.clientMessageId ?? null
    if (!clientRequestId) {
      return res.status(400).json({ code: 'missing_request_id', message: 'clientRequestId majburiy.' })
    }

    // Bound how many requests one account can start per hour. Checked before
    // the claim so a flood never creates chats or messages.
    const rateOk = await checkLimit(userId, 'chat_requests')
    if (!rateOk.allowed) {
      return res.status(429).json({ code: 'rate_limited', message: rateOk.message ?? 'Juda ko\'p so\'rov.' })
    }

    // Validate Talent ownership BEFORE claiming. A foreign or missing talentId
    // must never create a chat or insert a user message. V8 validated this
    // AFTER the claim, so an invalid talent still left an orphaned chat.  (V9 2.6)
    let talent: { id: string; name: string; description: string | null; instructions: string | null; subject_slug: string | null } | null = null
    if (body.talentId) {
      const { data } = await admin.from('skills').select('id,name,description,instructions,subject_slug').eq('id', body.talentId).eq('user_id', userId).maybeSingle()
      if (!data) return res.status(400).json({ message: 'Tanlangan Talent topilmadi.' })
      talent = data
    }

    const { data: claimRows, error: claimError } = await admin.rpc('claim_chat_request', {
      p_user_id: userId,
      p_client_request_id: clientRequestId,
      p_chat_id: body.chatId ?? null,
      p_text: body.text,
      p_attachments: media ? [{ name: media.name ?? 'biriktirma', mimeType: media.mimeType }] : null,
      p_title: question.replace(/\s+/g, ' ').trim().slice(0, 60) || 'Yangi suhbat',
      p_talent_id: body.talentId ?? null,
      p_lease_seconds: 180,
    })
    if (claimError) {
      if (claimError.code === '42501') {
        return res.status(404).json({ code: 'chat_not_found', message: 'Chat topilmadi yoki bu akkauntga tegishli emas.' })
      }
      throw claimError
    }

    const claim = Array.isArray(claimRows) ? claimRows[0] : claimRows
    if (!claim) throw new Error('claim_failed')

    const chatId: string = claim.chat_id
    const requestId: string = claim.request_id
    const leaseToken: string | null = claim.lease_token ?? null
    activeRequest = { userId, requestId, leaseToken }

    // Already answered: replay the stored result. No model call, no new rows.
    if (claim.outcome === 'completed') {
      const snapshot = (claim.response_snapshot ?? {}) as Record<string, unknown>
      return res.json({
        ...snapshot, chatId, messageId: snapshot.messageId ?? null,
        latencyMs: Date.now() - started, deduplicated: true,
      })
    }

    // Another attempt currently owns this request. The client polls
    // /api/chat/requests/:id rather than starting a second generation.
    if (claim.outcome === 'processing') {
      return res.status(202).json({
        code: 'processing', chatId, clientRequestId,
        message: 'So\'rov allaqachon bajarilmoqda.',
      })
    }

    // The provider may or may not have run before the crash. Re-invoking
    // could double-charge and produce a second answer, so we require an
    // explicit user decision instead of silently retrying.
    if (claim.outcome === 'uncertain') {
      return res.status(409).json({
        code: 'uncertain', chatId, clientRequestId,
        message: 'Oldingi urinish holati noaniq. Qayta yuborishni tasdiqlang.',
      })
    }

    // Talent already validated above; now link it to the claimed chat and
    // bump its usage counter.
    if (talent) {
      await admin.from('chats').update({ skill_id: talent.id }).eq('id', chatId).eq('user_id', userId)
      await admin.from('skills').update({ use_count: (await currentTalentUseCount(talent.id, userId)) + 1, updated_at: new Date().toISOString() }).eq('id', talent.id).eq('user_id', userId)
    }

    const route = await routeMessage(userId, question)
    if (route.intent === 'off_topic' && !talent) {
      const saved = await persist(userId, requestId, leaseToken, REFUSAL_BLOCKS, 'guard', started)
      return res.json({ ...saved, chatId, sourceMode: 'none', subject: null })
    }
    const subjectSlug = talent?.subject_slug ?? slash.subject ?? route.subject_slug

    let sourceIds: string[] = []
    let selectedSourceMeta: Array<{ id: string; title: string; status: string; page_count: number | null; storage_path: string | null; error_message: string | null; processing_warning: string | null }> = []
    let sourceMode: 'locked' | 'auto' | 'none' | 'not_found' = 'none'

    // New clients always send lockedSourceIds, including an empty array when
    // the user explicitly removes every source. Older clients may omit it;
    // in that case restore the account-synced source context of this chat.
    const sourceSelectionProvided = body.lockedSourceIds !== undefined || body.lockedSourceId !== undefined
    let requestedSourceIds = body.lockedSourceIds?.length
      ? [...new Set(body.lockedSourceIds)]
      : body.lockedSourceId ? [body.lockedSourceId] : []

    if (!sourceSelectionProvided) {
      const { data: remembered, error: rememberedError } = await admin
        .from('chat_sources')
        .select('source_id')
        .eq('chat_id', chatId)
        .eq('user_id', userId)
        .order('created_at', { ascending: true })
      if (rememberedError) throw rememberedError
      requestedSourceIds = (remembered ?? []).map((row) => row.source_id)
    }

    if (requestedSourceIds.length) {
      const { data: ownedSources, error } = await admin.from('sources').select('id,title,status,page_count,storage_path,error_message,processing_warning').eq('user_id', userId).in('id', requestedSourceIds)
      if (error) throw error
      if (!ownedSources?.length) return res.status(404).json({ message: 'Tanlangan manba bu akkauntda topilmadi.' })
      const unavailable = ownedSources.filter((s) => s.status !== 'ready')
      if (unavailable.length) {
        const src = unavailable[0]!
        return res.status(409).json({ message: src.status === 'failed' ? `“${src.title}” qayta ishlanmadi: ${src.error_message ?? 'noma’lum xato'}. Manbani qayta ishlang.` : `“${src.title}” hali tayyorlanmoqda (${src.status}).` })
      }
      // Preserve the user's requested order even though SQL IN does not.
      const sourceById = new Map(ownedSources.map((source) => [source.id, source]))
      selectedSourceMeta = requestedSourceIds.map((id) => sourceById.get(id)).filter(Boolean) as typeof selectedSourceMeta
      sourceIds = selectedSourceMeta.map((source) => source.id)
      sourceMode = 'locked'
    } else if (settings?.auto_source !== false && route.needs_source) {
      let subjectId: string | null = null
      if (subjectSlug) {
        const { data } = await admin.from('subjects').select('id').or(`user_id.eq.${userId},is_system.eq.true`).eq('slug', subjectSlug).limit(1).maybeSingle()
        subjectId = data?.id ?? null
      }
      let query = admin.from('sources').select('id').eq('user_id', userId).eq('status', 'ready').eq('is_active', true)
      if (subjectId) query = query.eq('subject_id', subjectId)
      const { data } = await query.limit(4)
      if (data?.length) { sourceIds = data.map((s) => s.id); sourceMode = 'auto' }
    }

    // Persist manual source context per chat and account. This is what makes
    // the same source selection reappear on another device after sign-in.
    if (sourceSelectionProvided) {
      const { error: clearSourceError } = await admin.from('chat_sources').delete().eq('chat_id', chatId).eq('user_id', userId)
      if (clearSourceError) throw clearSourceError
      if (sourceIds.length) {
        const { error: linkError } = await admin.from('chat_sources').insert(
          sourceIds.map((sourceId) => ({ chat_id: chatId, source_id: sourceId, user_id: userId }))
        )
        if (linkError) throw linkError
      }
      const { error: contextError } = await admin.from('chats').update({
        locked_source_id: sourceIds[0] ?? null,
        skill_id: talent?.id ?? body.talentId ?? null,
      }).eq('id', chatId).eq('user_id', userId)
      if (contextError) throw contextError
    }

    // Create the query vector only after the real account-owned source context
    // has been resolved. This prevents cached answers from a different source
    // being served before manual/automatic source selection is known.
    let questionEmbedding: number[] | null = null
    try { questionEmbedding = await embedOne(question, 'query') } catch { /* page/keyword/direct-PDF fallback remains available */ }

    const cacheAllowed = !media && !talent && sourceIds.length <= 1
    if (cacheAllowed && questionEmbedding) {
      try {
        const { data: cached } = await admin.rpc('match_answer_cache', {
          p_user_id: userId,
          p_embedding: questionEmbedding,
          p_source_id: sourceIds[0] ?? null,
          p_threshold: CACHE_THRESHOLD,
        })
        const hit = Array.isArray(cached) ? cached[0] : null
        if (hit?.answer_blocks) {
          const saved = await persist(userId, requestId, leaseToken, hit.answer_blocks, 'cache', started, {
            subject: route.subject,
            sourceId: sourceIds[0] ?? null,
            sourceMode,
          })
          return res.json({ ...saved, cached: true, chatId, sourceMode, subject: route.subject })
        }
      } catch { /* cache is an optimisation, never a hard dependency */ }
    }

    const pageHint = slash.page ?? route.page_hint ?? extractPage(question)
    let chunks: Chunk[] = []
    if (sourceIds.length && pageHint) chunks = await getPageContext(sourceIds, pageHint)
    if (sourceIds.length && chunks.length === 0 && questionEmbedding) chunks = await getVectorContext(userId, sourceIds, question, questionEmbedding)
    if (sourceIds.length && chunks.length === 0) chunks = await getKeywordContext(sourceIds, question)

    // Scanned/image PDFs have no text layer, so page/vector/keyword search
    // above always comes back empty for them. Sending the ENTIRE book inline
    // (sometimes 1000+ pages) is slow and, in practice, unreliable — the
    // model tends to give up rather than hunt through hundreds of images.
    // Instead we rasterize only the pages that matter: a small window around
    // the page the user mentioned, or a spread-out sample when no page was
    // given. This is the real fix for "found nothing" on scanned books.
    const sourcePdfMedia: Array<{ mimeType: string; data: string }> = []
    // Rendered PDF pages become page_image evidence: the model may cite them,
    // and the citation resolves back to a real rendered page, not a guess.
    const renderedEvidence: Array<{ sourceId: string; sourceTitle: string | null; pdfPage: number }> = []
    let renderedPageLabel: string | null = null
    if (requestedSourceIds.length && chunks.length === 0) {
      for (const src of selectedSourceMeta) {
        if (!src.storage_path) continue
        try {
          const { data: file, error: downloadError } = await admin.storage.from('sources').download(src.storage_path)
          if (downloadError || !file) { console.error('[source] download failed', src.id, downloadError); continue }
          const bytes = Buffer.from(await file.arrayBuffer())

          if (pageHint !== null) {
            // Centre the window on the REAL pdf index for this printed page,
            // resolved from the anchors/segments the worker recorded — not on
            // the printed number itself.  (V9 2.11)
            const { center, note } = await resolveRenderCenter(src.id, pageHint)
            const rendered = await renderPageWindow(bytes, center, src.page_count)
            if (rendered.length) {
              sourcePdfMedia.push(...rendered.map((p) => ({ mimeType: p.mimeType, data: p.data })))
              renderedEvidence.push(...rendered.map((p) => ({ sourceId: src.id, sourceTitle: src.title, pdfPage: p.pdfPage })))
              const first = rendered[0]!.pdfPage, last = rendered[rendered.length - 1]!.pdfPage
              renderedPageLabel = `${note} PDF ${first}-${last} betlari rasm sifatida biriktirildi.`
            }
          } else {
            const rendered = await renderSkimSample(bytes, src.page_count)
            if (rendered.length) {
              sourcePdfMedia.push(...rendered.map((p) => ({ mimeType: p.mimeType, data: p.data })))
              renderedEvidence.push(...rendered.map((p) => ({ sourceId: src.id, sourceTitle: src.title, pdfPage: p.pdfPage })))
              renderedPageLabel = `Bu ${src.page_count ?? '?'} betlik skanerlangan kitobdan tanlab olingan ${rendered.length} ta namuna bet (aniq bet raqami berilmagan). Agar javob shu betlarda bo'lmasa, foydalanuvchidan bet raqamini so'ra.`
            }
          }
        } catch (renderError) {
          console.error('[source] page render failed, falling back to raw PDF', src.id, renderError)
          // Rendering can fail on unusual PDF encodings. Fall back to the
          // old behaviour — the whole file, capped at 20 MB — rather than
          // silently giving up.
          try {
            const { data: file } = await admin.storage.from('sources').download(src.storage_path)
            if (file) {
              const bytes = Buffer.from(await file.arrayBuffer())
              if (bytes.length <= 20 * 1024 * 1024) sourcePdfMedia.push({ mimeType: 'application/pdf', data: bytes.toString('base64') })
            }
          } catch { /* out of options for this source */ }
        }
      }
    }

    const hasSource = chunks.length > 0 || sourcePdfMedia.length > 0
    if (sourceIds.length && !hasSource) sourceMode = 'not_found'

    // Honest coverage: if only part of a scanned book has been read, say so in
    // the prompt so the model can qualify its answer instead of implying it
    // searched the whole book. Also queue the pages the user actually needs.
    let coverageNote: string | null = null
    const primarySource = sourceIds[0]
    if (primarySource) {
      const coverage = await sourceCoverage(primarySource)
      if (coverage && !coverage.complete && coverage.totalPages > 0) {
        coverageNote = `QAMROV: ${coverage.totalPages} betdan ${coverage.searchablePages} beti o'qilgan` +
          (coverage.ocrTotal > 0 ? `, OCR ${coverage.ocrDone}/${coverage.ocrTotal}` : '') +
          `. To'liq kitob qidirilmadi — javob shu qamrov ichida. Agar topilmasa, buni ochiq ayt.`
      }
      if (pageHint !== null) {
        // The user named a page: read it (and its neighbours) before anything else.
        const center = await resolveRenderCenter(primarySource, pageHint)
        void prioritizePages(userId, primarySource, center.center - 1, center.center + 2).catch(() => undefined)
      } else if (coverage && !coverage.complete) {
        // No page number — let the table of contents pick candidate ranges to read.
        const ranges = await routeQuery(primarySource, question).catch(() => [])
        for (const r of ranges) void prioritizePages(userId, primarySource, r.fromPdfPage, r.toPdfPage).catch(() => undefined)
        if (ranges.length) {
          coverageNote = `${coverageNote ?? ''} Mundarijaga ko'ra mavzu ${ranges.map((r) => `${r.fromPdfPage}-${r.toPdfPage}`).join(', ')} betlar atrofida bo'lishi mumkin (bu faqat yo'naltiruvchi ma'lumot, dalil emas).`.trim()
        }
      }
    }

    if (sourceIds.length) await admin.from('sources').update({ last_used_at: new Date().toISOString() }).in('id', sourceIds).eq('user_id', userId)

    if (requestedSourceIds.length && !hasSource) {
      const blocks = [{ type: 'source_not_found', searched: pageHint ? `${pageHint}-bet va yaqin betlar` : question.slice(0, 120), nearby: [] }]
      const saved = await persist(userId, requestId, leaseToken, blocks, 'source-guard', started, { subject: route.subject, sourceId: sourceIds[0] ?? null, sourceMode: 'not_found' })
      return res.json({ ...saved, chatId, subject: route.subject, citations: [], sourceMode: 'not_found', pagesUsed: [] })
    }

    // Assemble the allowed evidence set. Text chunks carrying a real chunk id
    // become chunk-evidence; page/keyword rows become page-evidence; rendered
    // scans become page_image-evidence. The model may cite ONLY these ids.
    const evidenceItems: EvidenceItem[] = []
    for (const c of chunks) {
      const hasChunkId = typeof c.id === 'string' && c.id.length > 0
      evidenceItems.push({
        id: hasChunkId ? `chunk:${c.id}` : `page:${c.source_id}:${c.page_number}`,
        kind: hasChunkId ? 'chunk' : 'page',
        sourceId: c.source_id,
        sourceTitle: c.source_title ?? null,
        chunkId: hasChunkId ? c.id! : null,
        sourcePageId: null,
        pdfPageIndex: c.page_number,
        displayPage: c.page_number,
        printedPage: null,
        text: c.content,
      })
    }
    for (const r of renderedEvidence) {
      evidenceItems.push({
        id: `pageimg:${r.sourceId}:${r.pdfPage}`,
        kind: 'page_image',
        sourceId: r.sourceId,
        sourceTitle: r.sourceTitle,
        sourcePageId: null,
        chunkId: null,
        pdfPageIndex: r.pdfPage,
        displayPage: r.pdfPage,
        printedPage: null,
        text: null,
      })
    }
    // Structured items OCR detected on the pages in play (exercise 4, a table,
    // a formula). Citing "exercise:<id>" is far more precise than citing a page,
    // and it is still a server-issued ID the model cannot invent.
    if (primarySource && evidenceItems.length) {
      const pagesInPlay = [...new Set(evidenceItems.map((e) => e.pdfPageIndex).filter((n): n is number => typeof n === 'number'))].slice(0, 12)
      if (pagesInPlay.length) {
        const { data: items } = await admin
          .from('source_page_items')
          .select('id,source_id,pdf_page_index,item_kind,label,content')
          .eq('source_id', primarySource)
          .in('pdf_page_index', pagesInPlay)
          .in('item_kind', ['exercise', 'formula', 'table'])
          .limit(40)
        for (const item of items ?? []) {
          evidenceItems.push({
            id: `${item.item_kind}:${item.id}`,
            kind: item.item_kind as EvidenceItem['kind'],
            sourceId: item.source_id,
            sourceTitle: selectedSourceMeta.find((m) => m.id === item.source_id)?.title ?? null,
            sourcePageId: null,
            chunkId: null,
            pdfPageIndex: item.pdf_page_index,
            displayPage: item.pdf_page_index,
            printedPage: null,
            text: item.label ? `[${item.label}] ${item.content ?? ''}` : (item.content ?? null),
          })
        }
      }
    }

    const evidence = buildEvidence(evidenceItems)

    let system = buildSystemPrompt({
      grade: profile?.grade ?? null,
      language: profile?.school_language ?? 'uz',
      subjectSlug,
      answerLength,
      teacherMode: settings?.teacher_mode ?? false,
      stickerLevel: settings?.sticker_level ?? 'normal',
      citationRequired: settings?.citation_required ?? true,
      hasSource,
    })
    if (talent) {
      system += `\n\n## ACTIVE TALENT — QAT'IY DOMAIN LOCK\nNomi: ${talent.name}\nFan/mavzu: ${talent.subject_slug ?? 'umumiy'}\n${talent.instructions ?? talent.description ?? ''}\nBarcha matn, rasm, audio, fayl va manbani shu Talent doirasida talqin qil. Mavzu tashqarisidagi so‘rovni aralashtirma; mos kelmasa aniq ayt. Fakt uydirma.`
    }

    let prompt = ''
    if (hasSource) {
      const sourceNames = selectedSourceMeta.map((source) => source.title).filter(Boolean)
      prompt += INJECTION_GUARD
      prompt += `SOURCE_CONTEXT (faqat haqiqiy manba):\n`
      if (coverageNote) prompt += `${coverageNote}\n`
      if (sourceNames.length) prompt += `Ulangan manbalar: ${sourceNames.join(', ')}\n`
      if (evidence.promptBlock) prompt += `\n${evidence.promptBlock}\n`
      if (pageHint) prompt += `\nFOYDALANUVCHI ${pageHint}-BETNI AYTDI. PDF ichidagi BOSMA BET RAQAMINI PDF indeksidan ustun qo‘y. Muqova sabab indeks siljishi mumkin. ${pageHint}-betda uyga vazifa bo‘lmasa, yaqin betlardan haqiqiy uyga vazifa joyini top, o‘sha betni aniq ayt va shuni bajar. Hech qachon betni uydirma.\n`
      if (renderedPageLabel) prompt += `\nBIRIKTIRILGAN RASMLAR: ${renderedPageLabel}\n`
      prompt += EVIDENCE_CONTRACT
      prompt += '\n---\n'
    }
    if (slash.format === 'check') prompt += `TOPSHIRIQ: o‘quvchining javobini tekshir; xato joyini va to‘g‘ri javobni aniq ko‘rsat.\n`
    if (slash.format === 'simple') prompt += `TOPSHIRIQ: juda sodda tushuntir; hayotiy o‘xshatish, misol va bitta tekshiruv savoli ber.\n`
    if (slash.format === 'quiz') prompt += `TOPSHIRIQ: ${slash.quizCount ?? 5} ta quiz bloki yarat.\n`
    else if (slash.format === 'notebook') prompt += `TOPSHIRIQ: daftarga ko‘chirishga tayyor formatda ber.\n`
    if (slash.translate) prompt += `TARJIMA: ${slash.translate.from} → ${slash.translate.to}\n`
    prompt += `SAVOL: ${question}`

    // Recorded BEFORE the call. If the process dies after this point we can
    // no longer prove whether Gemini ran, so recovery marks the request
    // `uncertain` instead of silently invoking (and billing) it twice.
    await admin.rpc('mark_request_provider_started', {
      p_user_id: userId, p_request_id: requestId, p_lease_token: leaseToken, p_lease_seconds: 180,
    })

    // A long Gemini answer can outlive the request lease. The heartbeat
    // renews it every 60s and flips `lost` the instant another attempt
    // reclaims the request, so we never persist a result we no longer own.
    const heartbeat = startRequestHeartbeat(userId, requestId, leaseToken)
    let parsedResult: Parsed | null = null
    try {
      const raw = await generate({
        userId,
        model: MODELS.answer,
        system,
        prompt,
        json: true,
        media: [...sourcePdfMedia, ...(media ? [{ mimeType: media.mimeType, data: media.data }] : [])],
      })
      parsedResult = safeParse(raw)
      if (!parsedResult) {
        const retry = await generate({ userId, model: MODELS.answer, system: 'Faqat to‘g‘ri JSON qaytar.', prompt: `Quyidagini JSON formatga tuzat:\n${raw.slice(0, 5000)}`, json: true })
        parsedResult = safeParse(retry)
      }
      if (!parsedResult) parsedResult = { subject: route.subject, topic: '', blocks: [{ type: 'note', text: raw.slice(0, 3000) }], citations: [], stickers: [], confidence: 0.2, followups: [] }
    } finally {
      heartbeat.stop()
    }
    if (heartbeat.state.lost) {
      // Ownership was reclaimed mid-generation. Another attempt now owns this
      // request; persisting here would create a duplicate assistant message.
      return res.status(409).json({ code: 'lease_lost', chatId, clientRequestId, message: 'So\'rov boshqa urinishga o\'tdi. Iltimos qayta tekshiring.' })
    }
    // The try block always assigns a fallback, so this is defined; the guard
    // is only here to satisfy the compiler's cross-finally flow analysis.
    const parsed = parsedResult
    if (!parsed) throw new Error('parse_unreachable')

    // Evidence-locked: accept only the server-issued evidence IDs the model
    // actually cited, and take each page number from OUR record for that
    // evidence — never a page number the model invented.  (V9 2.10)
    // Repair the model's blocks BEFORE anything is persisted, so the stored
    // answer is already clean on every future read and on every device.
    parsed.blocks = normalizeBlocks(parsed.blocks)

    const ev = validateEvidence(parsed, evidence.allowed, hasSource)
    const citations = ev.citations
    const usedPages = new Set(ev.usedPages)
    const pageToSource = new Map(chunks.map((c) => [c.page_number, c.source_id]))
    const primarySourceId = chunks[0]?.source_id ?? sourceIds[0] ?? null
    const saved = await persist(userId, requestId, leaseToken, parsed.blocks, MODELS.answer, started, { subject: parsed.subject, sourceId: primarySourceId, sourceMode })

    if (citations.length && saved.messageId) {
      const { error } = await admin.from('message_citations').insert(citations.map((c) => ({ message_id: saved.messageId, source_id: pageToSource.get(c.page) ?? primarySourceId, page_number: c.page, quote: c.quote ?? null, ref: c.ref ?? null })))
      if (error) console.error('[citation]', error)
    }
    // Durable, machine-checkable proof of what each citation was grounded in.
    if (ev.rows.length && saved.messageId) {
      const { error } = await admin.from('message_evidence').insert(
        ev.rows.map((r) => ({ ...r, user_id: userId, message_id: saved.messageId }))
      )
      if (error) console.error('[evidence]', error)
    }
    if (cacheAllowed && questionEmbedding && parsed.confidence >= 0.6) {
      await admin.from('answer_cache').insert({ user_id: userId, source_id: sourceIds[0] ?? null, question, question_embedding: questionEmbedding, answer_blocks: parsed.blocks }).then(() => undefined, () => undefined)
    }
    await admin.from('activity_events').insert({ user_id: userId, kind: 'chat_message', chat_id: chatId, points: 2, metadata: { subject: parsed.subject, sourceMode, talentId: talent?.id ?? null } }).then(() => undefined, () => undefined)

    res.json({ ...saved, chatId, subject: parsed.subject, topic: parsed.topic, citations, stickers: parsed.stickers ?? [], followups: parsed.followups ?? [], confidence: parsed.confidence, sourceMode, pagesUsed: [...usedPages].sort((a,b)=>a-b), quotaPercent: await quotaPercent(userId) })
  } catch (e) {
    // Record the failure against the durable request so recovery can tell
    // "safe to retry" apart from "the provider may already have run".
    if (activeRequest) {
      await admin.rpc('fail_chat_request', {
        p_user_id: activeRequest.userId, p_request_id: activeRequest.requestId,
        p_lease_token: activeRequest.leaseToken,
        p_error_code: 'generation_failed',
        p_error_message: e instanceof Error ? e.message : 'unknown',
      }).then(() => undefined, () => undefined)
    }
    next(e)
  }
})

interface Parsed { subject: string; topic: string; blocks: unknown[]; citations?: { page: number; quote?: string; ref?: string }[]; evidenceIds?: string[]; stickers?: string[]; confidence: number; followups?: string[] }
function safeParse(raw: string): Parsed | null { try { const o = JSON.parse(stripFences(raw)) as Parsed; return Array.isArray(o.blocks) && o.blocks.length ? o : null } catch { return null } }

/**
 * Writes the answer through the atomic completion RPC.
 *
 * Every exit path — guard refusal, cache hit, source-not-found, and a real
 * model answer — goes through here, so a request can only ever end up with
 * one assistant message. The RPC verifies the lease, so an attempt whose
 * lease already expired cannot overwrite a result another attempt stored.
 */
async function persist(
  userId: string, requestId: string, leaseToken: string | null,
  blocks: unknown, model: string, started: number,
  meta?: { subject?: string; sourceId?: string | null; sourceMode?: string; snapshot?: Record<string, unknown> }
) {
  const latencyMs = Date.now() - started
  const snapshot = { ...(meta?.snapshot ?? {}), blocks, subject: meta?.subject ?? null, sourceMode: meta?.sourceMode ?? 'none' }

  const { data, error } = await admin.rpc('complete_chat_request', {
    p_user_id: userId,
    p_request_id: requestId,
    p_lease_token: leaseToken,
    p_blocks: blocks,
    p_snapshot: snapshot,
    p_subject: meta?.subject ?? null,
    p_source_mode: meta?.sourceMode ?? 'none',
    p_model_used: model,
    p_latency_ms: latencyMs,
  })
  if (error) throw error

  const row = Array.isArray(data) ? data[0] : data
  const messageId = row?.assistant_message_id ?? null
  // Keep the snapshot's messageId in sync so a later replay returns the
  // same id the first caller saw.
  if (messageId) {
    await admin.from('chat_requests')
      .update({ response_snapshot: { ...snapshot, messageId } })
      .eq('id', requestId).eq('user_id', userId)
  }
  return { messageId, blocks, latencyMs }
}

function extractPage(text: string): number | null { const m = text.match(/(?:^|\s)(\d{1,4})\s*(?:-|–)?\s*(?:bet|sahifa)/iu); return m?.[1] ? Number(m[1]) : null }
async function getPageContext(sourceIds: string[], page: number): Promise<Chunk[]> {
  const from = Math.max(1, page - 2), to = page + 1
  const { data: pages, error } = await admin.from('source_pages').select('source_id,page_number,text_content').in('source_id', sourceIds).gte('page_number', from).lte('page_number', to).order('page_number')
  if (error) throw error
  const { data: sources } = await admin.from('sources').select('id,title').in('id', sourceIds)
  const names = new Map<string, string>((sources ?? []).map((s) => [String(s.id), String(s.title)]))
  return (pages ?? []).filter((p) => (p.text_content ?? '').trim().length > 20).map((p) => ({ source_id: p.source_id, source_title: names.get(p.source_id), page_number: p.page_number, content: p.text_content.slice(0, 9000) }))
}
async function getVectorContext(userId: string, sourceIds: string[], question: string, embedding: number[]): Promise<Chunk[]> {
  const { data, error } = await admin.rpc('match_source_chunks', { p_user_id: userId, p_embedding: embedding, p_query_text: question, p_source_ids: sourceIds, p_page_from: null, p_page_to: null, p_match_count: 8 })
  if (error) return []
  const rows = (data as Chunk[]) ?? []
  const { data: sources } = await admin.from('sources').select('id,title').in('id', sourceIds)
  const names = new Map<string, string>((sources ?? []).map((s) => [String(s.id), String(s.title)]))
  return rows.map((r) => ({ ...r, source_title: names.get(r.source_id) }))
}
async function getKeywordContext(sourceIds: string[], question: string): Promise<Chunk[]> {
  const keyword = question.toLowerCase().match(/[\p{L}\p{N}]{5,}/gu)?.find((w) => !['qilib','bering','masala','vazifa','ushbu','kitob'].includes(w))
  if (!keyword) return []
  const safe = keyword.replace(/[%_,]/g, '')
  const { data } = await admin.from('source_pages').select('source_id,page_number,text_content').in('source_id', sourceIds).ilike('text_content', `%${safe}%`).limit(8)
  const { data: sources } = await admin.from('sources').select('id,title').in('id', sourceIds)
  const names = new Map<string, string>((sources ?? []).map((s) => [String(s.id), String(s.title)]))
  return (data ?? []).map((p) => ({ source_id: p.source_id, source_title: names.get(p.source_id), page_number: p.page_number, content: p.text_content.slice(0, 7000) }))
}
async function currentTalentUseCount(id: string, userId: string): Promise<number> { const { data } = await admin.from('skills').select('use_count').eq('id', id).eq('user_id', userId).maybeSingle(); return data?.use_count ?? 0 }

/** Opaque composite pagination cursor over (created_at, id). base64url so it
 *  survives a URL query param unescaped. */
function encodeCursor(createdAt: string, id: string): string {
  return Buffer.from(JSON.stringify({ t: createdAt, i: id }), 'utf8').toString('base64url')
}
function decodeCursor(raw: string): { t: string; i: string } | null {
  try {
    const parsed = JSON.parse(Buffer.from(raw, 'base64url').toString('utf8')) as { t?: unknown; i?: unknown }
    if (typeof parsed.t === 'string' && typeof parsed.i === 'string') return { t: parsed.t, i: parsed.i }
    return null
  } catch { return null }
}

/**
 * Recovery endpoint. If the HTTP response is lost — the phone slept, the
 * network dropped, the tab was closed — the client polls here with the same
 * clientRequestId and gets the persisted answer instead of re-asking Gemini.
 */
chatRouter.get('/requests/:clientRequestId', requireAuth, async (req, res, next) => {
  try {
    const userId = req.userId!
    const clientRequestId = req.params.clientRequestId ?? ''
    if (!/^[0-9a-f-]{36}$/i.test(clientRequestId)) {
      return res.status(400).json({ code: 'bad_request_id', message: 'Noto\'g\'ri so\'rov identifikatori.' })
    }

    const { data: request, error } = await admin
      .from('chat_requests')
      .select('id,status,chat_id,response_snapshot,error_code,error_message,assistant_message_id')
      .eq('user_id', userId)
      .eq('client_request_id', clientRequestId)
      .maybeSingle()
    if (error) throw error
    if (!request) return res.status(404).json({ code: 'not_found', message: 'So\'rov topilmadi.' })

    if (request.status === 'completed') {
      const snapshot = (request.response_snapshot ?? {}) as Record<string, unknown>
      return res.json({
        code: 'completed', chatId: request.chat_id,
        messageId: request.assistant_message_id, ...snapshot,
      })
    }
    if (request.status === 'claimed' || request.status === 'processing') {
      return res.json({ code: 'processing', chatId: request.chat_id })
    }
    if (request.status === 'uncertain') {
      return res.json({
        code: 'uncertain', chatId: request.chat_id,
        message: 'Oldingi urinish holati noaniq. Qayta yuborishni tasdiqlang.',
      })
    }
    return res.json({
      code: 'failed', chatId: request.chat_id,
      errorCode: request.error_code, message: request.error_message ?? 'So\'rov bajarilmadi.',
    })
  } catch (e) { next(e) }
})

chatRouter.get('/list', requireAuth, async (req, res, next) => { try { const { data, error } = await admin.from('chats').select('id,title,updated_at,pinned,project_id,archived,draft,skill_id,locked_source_id').eq('user_id', req.userId!).eq('archived', false).order('pinned', { ascending:false }).order('updated_at',{ascending:false}).limit(200); if(error)throw error; res.json({chats:data??[]}) } catch(e){next(e)} })
chatRouter.get('/search/:query', requireAuth, async (req,res,next)=>{ try{const q=(req.params.query??'').trim();if(q.length<2)return res.json({results:[]});const {data,error}=await admin.rpc('search_chats',{p_user_id:req.userId!,p_query:q,p_limit:30});if(error)throw error;res.json({results:data??[]})}catch(e){next(e)} })
chatRouter.get('/:chatId', requireAuth, async (req, res, next) => {
  try {
    const userId = req.userId!
    // Long chats must not ship hundreds of messages on open. We fetch the
    // NEWEST window (descending + limit) and reverse it for display; older
    // messages arrive on demand via ?before=<ISO timestamp>.
    const limit = Math.min(Math.max(Number(req.query.limit ?? 40) || 40, 10), 100)
    const rawCursor = typeof req.query.before === 'string' ? req.query.before : null
    const cursor = rawCursor ? decodeCursor(rawCursor) : null

    let messageQuery = admin
      .from('messages')
      .select('id,role,content,blocks,attachments,detected_subject,source_mode,created_at')
      .eq('chat_id', req.params.chatId)
      .eq('user_id', userId)
      .order('created_at', { ascending: false })
      .order('id', { ascending: false })
      .limit(limit + 1) // one extra row tells us whether more remain
    if (cursor) {
      // Composite keyset cursor: strictly older than (created_at, id). When
      // several messages share a created_at (a user + assistant pair inserted
      // in the same millisecond), the id tie-break stops a page boundary from
      // skipping or repeating a message.  (V9 2.9)
      messageQuery = messageQuery.or(`created_at.lt.${cursor.t},and(created_at.eq.${cursor.t},id.lt.${cursor.i})`)
    } else if (rawCursor) {
      // Backward compatibility: an older client may still send a bare ISO
      // timestamp. Fall back to the timestamp-only comparison for it.
      messageQuery = messageQuery.lt('created_at', rawCursor)
    }

    const [{ data: chat, error: chatError }, { data: newestFirst, error: messageError }, { data: links, error: linkError }] = await Promise.all([
      admin.from('chats').select('id,title,updated_at,pinned,project_id,draft,skill_id,locked_source_id').eq('id', req.params.chatId).eq('user_id', userId).maybeSingle(),
      messageQuery,
      admin.from('chat_sources').select('source_id').eq('chat_id', req.params.chatId).eq('user_id', userId).order('created_at', { ascending: true }),
    ])
    if (chatError) throw chatError
    if (!chat) return res.status(404).json({ message: 'Chat topilmadi yoki bu akkauntga tegishli emas.' })
    if (messageError) throw messageError
    if (linkError) throw linkError

    const rows = newestFirst ?? []
    const hasMore = rows.length > limit
    const page = hasMore ? rows.slice(0, limit) : rows
    const messages = [...page].reverse() // back to chronological for the UI
    const oldest = messages[0]
    const oldestCursor = oldest ? encodeCursor(String(oldest.created_at), String(oldest.id)) : null

    const sourceIds = (links ?? []).map((row) => row.source_id)
    if (!sourceIds.length && chat.locked_source_id) sourceIds.push(chat.locked_source_id)
    res.json({ chat, sourceIds, messages, hasMore, oldestCursor })
  } catch (e) { next(e) }
})
chatRouter.patch('/:chatId', requireAuth, async (req,res,next)=>{ try{const patch=z.object({title:z.string().min(1).max(120).optional(),pinned:z.boolean().optional(),archived:z.boolean().optional(),draft:z.string().max(8000).nullable().optional(),project_id:z.string().uuid().nullable().optional(),skill_id:z.string().uuid().nullable().optional(),locked_source_id:z.string().uuid().nullable().optional()}).parse(req.body);const {error}=await admin.from('chats').update(patch).eq('id',req.params.chatId).eq('user_id',req.userId!);if(error)throw error;res.json({ok:true})}catch(e){next(e)} })
chatRouter.delete('/:chatId', requireAuth, async (req,res,next)=>{ try{const {error}=await admin.from('chats').delete().eq('id',req.params.chatId).eq('user_id',req.userId!);if(error)throw error;res.json({ok:true})}catch(e){next(e)} })
