package com.veltrix.calculator.core

/**
 * V4 deterministic expansion catalog.
 *
 * This catalog is additive: Backend 1.1 registry entries remain canonical and are never shadowed.
 * Every entry declares an explicit formula, variable schema, solve targets and domain metadata.
 * No AI/LLM participates in calculation.
 */
internal object V4Catalog {
    const val EXPECTED_ADDITIONS = 93

    fun tools(): List<ToolDefinition> = listOf(
        formulaTool(
            id = "physics-g8-charge-quantization",
            title = "Charge Quantization",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Electric charge",
            display = "q = n*e",
            rules = mapOf("q" to "n*1.602176634e-19", "n" to "q/1.602176634e-19"),
            fields = listOf(InputFieldDefinition("q", "Charge", canonicalUnit = "C"), InputFieldDefinition("n", "Elementary-charge count", min = 0.0, allowNegative = false)),
            tags = setOf("grade8", "electricity"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-charge-conservation",
            title = "Charge Conservation",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Charge conservation",
            display = "Qfinal = Qinitial + Qtransfer",
            rules = mapOf("Qfinal" to "Qinitial+Qtransfer", "Qinitial" to "Qfinal-Qtransfer", "Qtransfer" to "Qfinal-Qinitial"),
            fields = listOf(InputFieldDefinition("Qfinal", "Final charge", canonicalUnit = "C"), InputFieldDefinition("Qinitial", "Initial charge", canonicalUnit = "C"), InputFieldDefinition("Qtransfer", "Transferred charge", canonicalUnit = "C")),
            tags = setOf("grade8"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-coulomb",
            title = "Coulomb Force",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Electrostatics",
            display = "F = k*|q1*q2|/r^2",
            rules = mapOf("F" to "8.9875517923e9*abs(q1*q2)/r^2", "q1" to "F*r^2/(8.9875517923e9*q2)", "q2" to "F*r^2/(8.9875517923e9*q1)", "r" to "sqrt(8.9875517923e9*abs(q1*q2)/F)"),
            fields = listOf(InputFieldDefinition("F", "Force", canonicalUnit = "N", unitCategory = "Force", min = 0.0, allowNegative = false), InputFieldDefinition("q1", "Charge 1", canonicalUnit = "C"), InputFieldDefinition("q2", "Charge 2", canonicalUnit = "C"), InputFieldDefinition("r", "Separation", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf("grade8", "electrostatics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-electric-field",
            title = "Electric Field Strength",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Electric field",
            display = "E = F/q",
            rules = mapOf("E" to "F/q", "F" to "E*q", "q" to "F/E"),
            fields = listOf(InputFieldDefinition("E", "Electric field", canonicalUnit = "N/C"), InputFieldDefinition("F", "Force", canonicalUnit = "N", unitCategory = "Force"), InputFieldDefinition("q", "Test charge", canonicalUnit = "C")),
            tags = setOf("grade8"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-point-charge-field",
            title = "Point Charge Electric Field",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Electric field",
            display = "E = k*|Q|/r^2",
            rules = mapOf("E" to "8.9875517923e9*abs(Q)/r^2", "Q" to "E*r^2/8.9875517923e9", "r" to "sqrt(8.9875517923e9*abs(Q)/E)"),
            fields = listOf(InputFieldDefinition("E", "Electric field", canonicalUnit = "N/C", min = 0.0, allowNegative = false), InputFieldDefinition("Q", "Source charge", canonicalUnit = "C"), InputFieldDefinition("r", "Distance", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf("grade8"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-electric-potential-work",
            title = "Electric Potential / Work",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Electric potential",
            display = "V = W/q",
            rules = mapOf("V" to "W/q", "W" to "V*q", "q" to "W/V"),
            fields = listOf(InputFieldDefinition("V", "Potential difference", canonicalUnit = "V", unitCategory = "Voltage"), InputFieldDefinition("W", "Work", canonicalUnit = "J", unitCategory = "Energy"), InputFieldDefinition("q", "Charge", canonicalUnit = "C")),
            tags = setOf("grade8"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-capacitance",
            title = "Capacitance",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Capacitors",
            display = "C = Q/V",
            rules = mapOf("C" to "Q/V", "Q" to "C*V", "V" to "Q/C"),
            fields = listOf(InputFieldDefinition("C", "Capacitance", canonicalUnit = "F"), InputFieldDefinition("Q", "Charge", canonicalUnit = "C"), InputFieldDefinition("V", "Voltage", canonicalUnit = "V", unitCategory = "Voltage")),
            tags = setOf("grade8"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-capacitor-energy",
            title = "Capacitor Energy",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Capacitors",
            display = "U = C*V^2/2",
            rules = mapOf("U" to "C*V^2/2", "C" to "2*U/V^2", "V" to "sqrt(2*U/C)"),
            fields = listOf(InputFieldDefinition("U", "Stored energy", canonicalUnit = "J", unitCategory = "Energy", min = 0.0, allowNegative = false), InputFieldDefinition("C", "Capacitance", canonicalUnit = "F", min = 0.0, allowNegative = false), InputFieldDefinition("V", "Voltage", canonicalUnit = "V", unitCategory = "Voltage", min = 0.0, allowNegative = false)),
            tags = setOf("grade8"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-current-charge-time",
            title = "Electric Current",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Current",
            display = "I = Q/t",
            rules = mapOf("I" to "Q/t", "Q" to "I*t", "t" to "Q/I"),
            fields = listOf(InputFieldDefinition("I", "Current", canonicalUnit = "A", unitCategory = "Current"), InputFieldDefinition("Q", "Charge", canonicalUnit = "C"), InputFieldDefinition("t", "Time", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false)),
            tags = setOf("grade8"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-resistivity",
            title = "Resistance and Resistivity",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Resistance",
            display = "R = rho*L/A",
            rules = mapOf("R" to "rho*L/A", "rho" to "R*A/L", "L" to "R*A/rho", "A" to "rho*L/R"),
            fields = listOf(InputFieldDefinition("R", "Resistance", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false), InputFieldDefinition("rho", "Resistivity", canonicalUnit = "ohm*m", min = 0.0, allowNegative = false), InputFieldDefinition("L", "Length", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false), InputFieldDefinition("A", "Area", canonicalUnit = "m2", unitCategory = "Area", min = 0.0, allowNegative = false)),
            tags = setOf("grade8"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-series-resistance",
            title = "Series Resistance",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Circuit combinations",
            display = "Req = R1 + R2",
            rules = mapOf("Req" to "R1+R2", "R1" to "Req-R2", "R2" to "Req-R1"),
            fields = listOf(InputFieldDefinition("Req", "Equivalent resistance", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false), InputFieldDefinition("R1", "Resistance 1", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false), InputFieldDefinition("R2", "Resistance 2", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false)),
            tags = setOf("grade8", "circuits"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-parallel-resistance-two",
            title = "Parallel Resistance (Two Resistors)",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Circuit combinations",
            display = "Req = R1*R2/(R1+R2)",
            rules = mapOf("Req" to "R1*R2/(R1+R2)", "R1" to "Req*R2/(R2-Req)", "R2" to "Req*R1/(R1-Req)"),
            fields = listOf(InputFieldDefinition("Req", "Equivalent resistance", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false), InputFieldDefinition("R1", "Resistance 1", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false), InputFieldDefinition("R2", "Resistance 2", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false)),
            tags = setOf("grade8", "circuits"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-voltage-divider",
            title = "Voltage Divider",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Circuit voltage",
            display = "Vout = Vin*R2/(R1+R2)",
            rules = mapOf("Vout" to "Vin*R2/(R1+R2)", "Vin" to "Vout*(R1+R2)/R2", "R1" to "R2*(Vin/Vout-1)", "R2" to "Vout*R1/(Vin-Vout)"),
            fields = listOf(InputFieldDefinition("Vout", "Output voltage", canonicalUnit = "V", unitCategory = "Voltage"), InputFieldDefinition("Vin", "Input voltage", canonicalUnit = "V", unitCategory = "Voltage"), InputFieldDefinition("R1", "Resistance 1", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false), InputFieldDefinition("R2", "Resistance 2", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false)),
            tags = setOf("grade8", "circuits"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-current-divider-two",
            title = "Current Divider (Two Branches)",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Circuit current",
            display = "I1 = It*R2/(R1+R2)",
            rules = mapOf("I1" to "It*R2/(R1+R2)", "It" to "I1*(R1+R2)/R2", "R1" to "R2*(It/I1-1)", "R2" to "I1*R1/(It-I1)"),
            fields = listOf(InputFieldDefinition("I1", "Branch current", canonicalUnit = "A", unitCategory = "Current"), InputFieldDefinition("It", "Total current", canonicalUnit = "A", unitCategory = "Current"), InputFieldDefinition("R1", "Branch resistance 1", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false), InputFieldDefinition("R2", "Branch resistance 2", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false)),
            tags = setOf("grade8", "circuits"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-joule-lenz",
            title = "Joule–Lenz Heat",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Electrical heating",
            display = "Q = I^2*R*t",
            rules = mapOf("Q" to "I^2*R*t", "I" to "sqrt(Q/(R*t))", "R" to "Q/(I^2*t)", "t" to "Q/(I^2*R)"),
            fields = listOf(InputFieldDefinition("Q", "Heat", canonicalUnit = "J", unitCategory = "Energy", min = 0.0, allowNegative = false), InputFieldDefinition("I", "Current", canonicalUnit = "A", unitCategory = "Current", min = 0.0, allowNegative = false), InputFieldDefinition("R", "Resistance", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false), InputFieldDefinition("t", "Time", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false)),
            tags = setOf("grade8", "electricity"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-electrical-energy",
            title = "Electrical Energy / Power / Time",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Electrical work and power",
            display = "E = P*t",
            rules = mapOf("E" to "P*t", "P" to "E/t", "t" to "E/P"),
            fields = listOf(InputFieldDefinition("E", "Energy", canonicalUnit = "J", unitCategory = "Energy", min = 0.0, allowNegative = false), InputFieldDefinition("P", "Power", canonicalUnit = "W", unitCategory = "Power", min = 0.0, allowNegative = false), InputFieldDefinition("t", "Time", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false)),
            tags = setOf("grade8", "electricity"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-efficiency",
            title = "Electrical Efficiency",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Efficiency",
            display = "eta = useful/input*100",
            rules = mapOf("eta" to "useful/input*100", "useful" to "eta*input/100", "input" to "useful*100/eta"),
            fields = listOf(InputFieldDefinition("eta", "Efficiency", canonicalUnit = "%", min = 0.0, max = 100.0, allowNegative = false), InputFieldDefinition("useful", "Useful energy/power", min = 0.0, allowNegative = false), InputFieldDefinition("input", "Input energy/power", min = 0.0, allowNegative = false)),
            tags = setOf("grade8"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-electrolysis-faraday",
            title = "Electrolysis / Faraday Relation",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Current in media",
            display = "m = k*I*t",
            rules = mapOf("m" to "k*I*t", "k" to "m/(I*t)", "I" to "m/(k*t)", "t" to "m/(k*I)"),
            fields = listOf(InputFieldDefinition("m", "Deposited mass", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("k", "Electrochemical equivalent", canonicalUnit = "kg/C", min = 0.0, allowNegative = false), InputFieldDefinition("I", "Current", canonicalUnit = "A", unitCategory = "Current", min = 0.0, allowNegative = false), InputFieldDefinition("t", "Time", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false)),
            tags = setOf("grade8", "electrolysis"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-magnetic-force-wire",
            title = "Ampere Force on a Current-Carrying Wire",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Magnetic field",
            display = "F = B*I*L*sin(theta)",
            rules = mapOf("F" to "B*I*L*sin(theta)", "B" to "F/(I*L*sin(theta))", "I" to "F/(B*L*sin(theta))", "L" to "F/(B*I*sin(theta))"),
            fields = listOf(InputFieldDefinition("F", "Force", canonicalUnit = "N", unitCategory = "Force"), InputFieldDefinition("B", "Magnetic flux density", canonicalUnit = "T"), InputFieldDefinition("I", "Current", canonicalUnit = "A", unitCategory = "Current"), InputFieldDefinition("L", "Wire length", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false), InputFieldDefinition("theta", "Angle", canonicalUnit = "rad", unitCategory = "Angle")),
            tags = setOf("grade8", "magnetism"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-lorentz-force",
            title = "Lorentz Magnetic Force",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Magnetic field",
            display = "F = q*v*B*sin(theta)",
            rules = mapOf("F" to "q*v*B*sin(theta)", "q" to "F/(v*B*sin(theta))", "v" to "F/(q*B*sin(theta))", "B" to "F/(q*v*sin(theta))"),
            fields = listOf(InputFieldDefinition("F", "Force", canonicalUnit = "N", unitCategory = "Force"), InputFieldDefinition("q", "Charge", canonicalUnit = "C"), InputFieldDefinition("v", "Speed", canonicalUnit = "m/s", unitCategory = "Speed"), InputFieldDefinition("B", "Magnetic flux density", canonicalUnit = "T"), InputFieldDefinition("theta", "Angle", canonicalUnit = "rad", unitCategory = "Angle")),
            tags = setOf("grade8", "magnetism"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-charged-particle-radius",
            title = "Charged Particle Radius in Magnetic Field",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Magnetic field",
            display = "r = m*v/(|q|*B)",
            rules = mapOf("r" to "m*v/(abs(q)*B)", "m" to "r*abs(q)*B/v", "v" to "r*abs(q)*B/m", "B" to "m*v/(abs(q)*r)"),
            fields = listOf(InputFieldDefinition("r", "Radius", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false), InputFieldDefinition("m", "Particle mass", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("v", "Speed", canonicalUnit = "m/s", unitCategory = "Speed", min = 0.0, allowNegative = false), InputFieldDefinition("q", "Charge", canonicalUnit = "C"), InputFieldDefinition("B", "Magnetic flux density", canonicalUnit = "T", min = 0.0, allowNegative = false)),
            tags = setOf("grade8", "magnetism"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-magnetic-flux",
            title = "Magnetic Flux",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Electromagnetic phenomena",
            display = "Phi = B*A*cos(theta)",
            rules = mapOf("Phi" to "B*A*cos(theta)", "B" to "Phi/(A*cos(theta))", "A" to "Phi/(B*cos(theta))"),
            fields = listOf(InputFieldDefinition("Phi", "Magnetic flux", canonicalUnit = "Wb"), InputFieldDefinition("B", "Magnetic flux density", canonicalUnit = "T"), InputFieldDefinition("A", "Area", canonicalUnit = "m2", unitCategory = "Area", min = 0.0, allowNegative = false), InputFieldDefinition("theta", "Angle", canonicalUnit = "rad", unitCategory = "Angle")),
            tags = setOf("grade8", "induction"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-faraday",
            title = "Faraday Induction",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Electromagnetic induction",
            display = "emf = -N*dPhi/dt",
            rules = mapOf("emf" to "-N*dPhi/dt", "N" to "-emf*dt/dPhi", "dPhi" to "-emf*dt/N", "dt" to "-N*dPhi/emf"),
            fields = listOf(InputFieldDefinition("emf", "Induced emf", canonicalUnit = "V", unitCategory = "Voltage"), InputFieldDefinition("N", "Turns", min = 1.0, allowNegative = false), InputFieldDefinition("dPhi", "Flux change", canonicalUnit = "Wb"), InputFieldDefinition("dt", "Time interval", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false)),
            tags = setOf("grade8", "induction"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-transformer-voltage",
            title = "Ideal Transformer Voltage Ratio",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Transformers",
            display = "Vs/Vp = Ns/Np",
            rules = mapOf("Vs" to "Vp*Ns/Np", "Vp" to "Vs*Np/Ns", "Ns" to "Vs*Np/Vp", "Np" to "Vp*Ns/Vs"),
            fields = listOf(InputFieldDefinition("Vs", "Secondary voltage", canonicalUnit = "V", unitCategory = "Voltage"), InputFieldDefinition("Vp", "Primary voltage", canonicalUnit = "V", unitCategory = "Voltage"), InputFieldDefinition("Ns", "Secondary turns", min = 1.0, allowNegative = false), InputFieldDefinition("Np", "Primary turns", min = 1.0, allowNegative = false)),
            tags = setOf("grade8", "induction"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g8-transformer-current",
            title = "Ideal Transformer Current Ratio",
            subject = Subject.PHYSICS,
            category = "Grade 8 Physics",
            topic = "Transformers",
            display = "Is/Ip = Np/Ns",
            rules = mapOf("Is" to "Ip*Np/Ns", "Ip" to "Is*Ns/Np", "Np" to "Is*Ns/Ip", "Ns" to "Ip*Np/Is"),
            fields = listOf(InputFieldDefinition("Is", "Secondary current", canonicalUnit = "A", unitCategory = "Current"), InputFieldDefinition("Ip", "Primary current", canonicalUnit = "A", unitCategory = "Current"), InputFieldDefinition("Np", "Primary turns", min = 1.0, allowNegative = false), InputFieldDefinition("Ns", "Secondary turns", min = 1.0, allowNegative = false)),
            tags = setOf("grade8", "induction"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-linear-expansion",
            title = "Linear Thermal Expansion",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Thermal expansion",
            display = "dL = alpha*L0*dT",
            rules = mapOf("dL" to "alpha*L0*dT", "alpha" to "dL/(L0*dT)", "L0" to "dL/(alpha*dT)", "dT" to "dL/(alpha*L0)"),
            fields = listOf(InputFieldDefinition("dL", "Length change", canonicalUnit = "m", unitCategory = "Length"), InputFieldDefinition("alpha", "Linear expansion coefficient", canonicalUnit = "1/K"), InputFieldDefinition("L0", "Initial length", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false), InputFieldDefinition("dT", "Temperature change", canonicalUnit = "K")),
            tags = setOf("grade9", "thermal"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-calorimetry-balance",
            title = "Calorimetry Balance",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Heat balance",
            display = "m1*c1*(Tf-T1)+m2*c2*(Tf-T2)=0",
            rules = mapOf("Tf" to "(m1*c1*T1+m2*c2*T2)/(m1*c1+m2*c2)"),
            fields = listOf(InputFieldDefinition("Tf", "Final temperature", canonicalUnit = "K"), InputFieldDefinition("m1", "Mass 1", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("c1", "Specific heat 1", canonicalUnit = "J/(kg*K)", min = 0.0, allowNegative = false), InputFieldDefinition("T1", "Initial temperature 1", canonicalUnit = "K"), InputFieldDefinition("m2", "Mass 2", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("c2", "Specific heat 2", canonicalUnit = "J/(kg*K)", min = 0.0, allowNegative = false), InputFieldDefinition("T2", "Initial temperature 2", canonicalUnit = "K")),
            tags = setOf("grade9", "thermal"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-latent-heat",
            title = "Latent Heat",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Phase change",
            display = "Q = m*L",
            rules = mapOf("Q" to "m*L", "m" to "Q/L", "L" to "Q/m"),
            fields = listOf(InputFieldDefinition("Q", "Heat", canonicalUnit = "J", unitCategory = "Energy"), InputFieldDefinition("m", "Mass", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("L", "Specific latent heat", canonicalUnit = "J/kg", min = 0.0, allowNegative = false)),
            tags = setOf("grade9", "thermal"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-boyle",
            title = "Boyle's Law",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Gas laws",
            display = "P1*V1=P2*V2",
            rules = mapOf("P1" to "P2*V2/V1", "V1" to "P2*V2/P1", "P2" to "P1*V1/V2", "V2" to "P1*V1/P2"),
            fields = listOf(InputFieldDefinition("P1", "Initial pressure", canonicalUnit = "Pa", unitCategory = "Pressure", min = 0.0, allowNegative = false), InputFieldDefinition("V1", "Initial volume", canonicalUnit = "m3", unitCategory = "Volume", min = 0.0, allowNegative = false), InputFieldDefinition("P2", "Final pressure", canonicalUnit = "Pa", unitCategory = "Pressure", min = 0.0, allowNegative = false), InputFieldDefinition("V2", "Final volume", canonicalUnit = "m3", unitCategory = "Volume", min = 0.0, allowNegative = false)),
            tags = setOf("grade9", "gas"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-charles",
            title = "Charles's Law",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Gas laws",
            display = "V1/T1=V2/T2",
            rules = mapOf("V1" to "V2*T1/T2", "T1" to "V1*T2/V2", "V2" to "V1*T2/T1", "T2" to "V2*T1/V1"),
            fields = listOf(InputFieldDefinition("V1", "Initial volume", canonicalUnit = "m3", unitCategory = "Volume", min = 0.0, allowNegative = false), InputFieldDefinition("T1", "Initial absolute temperature", canonicalUnit = "K", min = 0.0, allowNegative = false), InputFieldDefinition("V2", "Final volume", canonicalUnit = "m3", unitCategory = "Volume", min = 0.0, allowNegative = false), InputFieldDefinition("T2", "Final absolute temperature", canonicalUnit = "K", min = 0.0, allowNegative = false)),
            tags = setOf("grade9", "gas"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-combined-gas",
            title = "Combined Gas Law",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Gas laws",
            display = "P1*V1/T1=P2*V2/T2",
            rules = mapOf("P1" to "P2*V2*T1/(T2*V1)", "V1" to "P2*V2*T1/(T2*P1)", "T1" to "P1*V1*T2/(P2*V2)", "P2" to "P1*V1*T2/(T1*V2)", "V2" to "P1*V1*T2/(T1*P2)", "T2" to "P2*V2*T1/(P1*V1)"),
            fields = listOf(InputFieldDefinition("P1", "Initial pressure", canonicalUnit = "Pa", unitCategory = "Pressure", min = 0.0, allowNegative = false), InputFieldDefinition("V1", "Initial volume", canonicalUnit = "m3", unitCategory = "Volume", min = 0.0, allowNegative = false), InputFieldDefinition("T1", "Initial temperature", canonicalUnit = "K", min = 0.0, allowNegative = false), InputFieldDefinition("P2", "Final pressure", canonicalUnit = "Pa", unitCategory = "Pressure", min = 0.0, allowNegative = false), InputFieldDefinition("V2", "Final volume", canonicalUnit = "m3", unitCategory = "Volume", min = 0.0, allowNegative = false), InputFieldDefinition("T2", "Final temperature", canonicalUnit = "K", min = 0.0, allowNegative = false)),
            tags = setOf("grade9", "gas"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-surface-tension",
            title = "Surface Tension Force",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Fluids",
            display = "F=gamma*L",
            rules = mapOf("F" to "gamma*L", "gamma" to "F/L", "L" to "F/gamma"),
            fields = listOf(InputFieldDefinition("F", "Force", canonicalUnit = "N", unitCategory = "Force"), InputFieldDefinition("gamma", "Surface tension", canonicalUnit = "N/m", min = 0.0, allowNegative = false), InputFieldDefinition("L", "Contact length", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf("grade9", "fluid"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-capillary-rise",
            title = "Capillary Rise",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Fluids",
            display = "h=2*gamma*cos(theta)/(rho*g*r)",
            rules = mapOf("h" to "2*gamma*cos(theta)/(rho*g*r)", "gamma" to "h*rho*g*r/(2*cos(theta))", "r" to "2*gamma*cos(theta)/(rho*g*h)"),
            fields = listOf(InputFieldDefinition("h", "Rise height", canonicalUnit = "m", unitCategory = "Length"), InputFieldDefinition("gamma", "Surface tension", canonicalUnit = "N/m", min = 0.0, allowNegative = false), InputFieldDefinition("theta", "Contact angle", canonicalUnit = "rad", unitCategory = "Angle"), InputFieldDefinition("rho", "Density", canonicalUnit = "kg/m3", unitCategory = "Density", min = 0.0, allowNegative = false), InputFieldDefinition("g", "Gravity", canonicalUnit = "m/s2", unitCategory = "Acceleration", min = 0.0, allowNegative = false), InputFieldDefinition("r", "Tube radius", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf("grade9", "fluid"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-snell",
            title = "Snell's Law",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Optics",
            display = "n1*sin(theta1)=n2*sin(theta2)",
            rules = mapOf("n1" to "n2*sin(theta2)/sin(theta1)", "n2" to "n1*sin(theta1)/sin(theta2)", "theta1" to "asin(n2*sin(theta2)/n1)", "theta2" to "asin(n1*sin(theta1)/n2)"),
            fields = listOf(InputFieldDefinition("n1", "Refractive index 1", min = 1.0, allowNegative = false), InputFieldDefinition("theta1", "Incident angle", canonicalUnit = "rad", unitCategory = "Angle"), InputFieldDefinition("n2", "Refractive index 2", min = 1.0, allowNegative = false), InputFieldDefinition("theta2", "Refracted angle", canonicalUnit = "rad", unitCategory = "Angle")),
            tags = setOf("grade9", "optics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-critical-angle",
            title = "Critical Angle",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Optics",
            display = "thetaC=asin(n2/n1)",
            rules = mapOf("thetaC" to "asin(n2/n1)", "n2" to "n1*sin(thetaC)", "n1" to "n2/sin(thetaC)"),
            fields = listOf(InputFieldDefinition("thetaC", "Critical angle", canonicalUnit = "rad", unitCategory = "Angle"), InputFieldDefinition("n1", "Higher refractive index", min = 1.0, allowNegative = false), InputFieldDefinition("n2", "Lower refractive index", min = 1.0, allowNegative = false)),
            tags = setOf("grade9", "optics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-lens-magnification",
            title = "Lens Magnification",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Optics",
            display = "M=-di/do",
            rules = mapOf("M" to "-di/do", "di" to "-M*do", "do" to "-di/M"),
            fields = listOf(InputFieldDefinition("M", "Magnification"), InputFieldDefinition("di", "Image distance", canonicalUnit = "m", unitCategory = "Length"), InputFieldDefinition("do", "Object distance", canonicalUnit = "m", unitCategory = "Length")),
            tags = setOf("grade9", "optics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-lens-power",
            title = "Lens Power",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Optics",
            display = "P=1/f",
            rules = mapOf("P" to "1/f", "f" to "1/P"),
            fields = listOf(InputFieldDefinition("P", "Power", canonicalUnit = "D"), InputFieldDefinition("f", "Focal length", canonicalUnit = "m", unitCategory = "Length")),
            tags = setOf("grade9", "optics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-refractive-index-speed",
            title = "Refractive Index and Light Speed",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Optics",
            display = "n=c/v",
            rules = mapOf("n" to "299792458/v", "v" to "299792458/n"),
            fields = listOf(InputFieldDefinition("n", "Refractive index", min = 1.0, allowNegative = false), InputFieldDefinition("v", "Light speed in medium", canonicalUnit = "m/s", unitCategory = "Speed", min = 0.0, allowNegative = false)),
            tags = setOf("grade9", "optics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-frequency-wavelength",
            title = "Wave Speed, Frequency and Wavelength",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Waves",
            display = "v=f*lambda",
            rules = mapOf("v" to "f*lambda", "f" to "v/lambda", "lambda" to "v/f"),
            fields = listOf(InputFieldDefinition("v", "Wave speed", canonicalUnit = "m/s", unitCategory = "Speed"), InputFieldDefinition("f", "Frequency", canonicalUnit = "Hz", unitCategory = "Frequency", min = 0.0, allowNegative = false), InputFieldDefinition("lambda", "Wavelength", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf("grade9", "waves"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g9-wave-period",
            title = "Wave Period and Frequency",
            subject = Subject.PHYSICS,
            category = "Grade 9 Physics",
            topic = "Waves",
            display = "T=1/f",
            rules = mapOf("T" to "1/f", "f" to "1/T"),
            fields = listOf(InputFieldDefinition("T", "Period", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false), InputFieldDefinition("f", "Frequency", canonicalUnit = "Hz", unitCategory = "Frequency", min = 0.0, allowNegative = false)),
            tags = setOf("grade9", "waves"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-kinematics-displacement",
            title = "Uniformly Accelerated Displacement",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Kinematics",
            display = "s=v0*t+a*t^2/2",
            rules = mapOf("s" to "v0*t+a*t^2/2", "v0" to "(s-a*t^2/2)/t", "a" to "2*(s-v0*t)/t^2"),
            fields = listOf(InputFieldDefinition("s", "Displacement", canonicalUnit = "m", unitCategory = "Length"), InputFieldDefinition("v0", "Initial velocity", canonicalUnit = "m/s", unitCategory = "Speed"), InputFieldDefinition("a", "Acceleration", canonicalUnit = "m/s2", unitCategory = "Acceleration"), InputFieldDefinition("t", "Time", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false)),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-kinematics-velocity",
            title = "Uniformly Accelerated Velocity",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Kinematics",
            display = "v=v0+a*t",
            rules = mapOf("v" to "v0+a*t", "v0" to "v-a*t", "a" to "(v-v0)/t", "t" to "(v-v0)/a"),
            fields = listOf(InputFieldDefinition("v", "Final velocity", canonicalUnit = "m/s", unitCategory = "Speed"), InputFieldDefinition("v0", "Initial velocity", canonicalUnit = "m/s", unitCategory = "Speed"), InputFieldDefinition("a", "Acceleration", canonicalUnit = "m/s2", unitCategory = "Acceleration"), InputFieldDefinition("t", "Time", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false)),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-kinematics-no-time",
            title = "Kinematics Without Time",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Kinematics",
            display = "v^2=v0^2+2*a*s",
            rules = mapOf("v" to "sqrt(v0^2+2*a*s)", "v0" to "sqrt(v^2-2*a*s)", "a" to "(v^2-v0^2)/(2*s)", "s" to "(v^2-v0^2)/(2*a)"),
            fields = listOf(InputFieldDefinition("v", "Final speed", canonicalUnit = "m/s", unitCategory = "Speed", min = 0.0, allowNegative = false), InputFieldDefinition("v0", "Initial speed", canonicalUnit = "m/s", unitCategory = "Speed", min = 0.0, allowNegative = false), InputFieldDefinition("a", "Acceleration", canonicalUnit = "m/s2", unitCategory = "Acceleration"), InputFieldDefinition("s", "Displacement", canonicalUnit = "m", unitCategory = "Length")),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-newton-second",
            title = "Newton's Second Law",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Dynamics",
            display = "F=m*a",
            rules = mapOf("F" to "m*a", "m" to "F/a", "a" to "F/m"),
            fields = listOf(InputFieldDefinition("F", "Net force", canonicalUnit = "N", unitCategory = "Force"), InputFieldDefinition("m", "Mass", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("a", "Acceleration", canonicalUnit = "m/s2", unitCategory = "Acceleration")),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-weight",
            title = "Weight",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Dynamics",
            display = "W=m*g",
            rules = mapOf("W" to "m*g", "m" to "W/g", "g" to "W/m"),
            fields = listOf(InputFieldDefinition("W", "Weight", canonicalUnit = "N", unitCategory = "Force", min = 0.0, allowNegative = false), InputFieldDefinition("m", "Mass", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("g", "Gravity", canonicalUnit = "m/s2", unitCategory = "Acceleration", min = 0.0, allowNegative = false)),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-friction",
            title = "Friction Force",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Dynamics",
            display = "Ff=mu*N",
            rules = mapOf("Ff" to "mu*N", "mu" to "Ff/N", "N" to "Ff/mu"),
            fields = listOf(InputFieldDefinition("Ff", "Friction force", canonicalUnit = "N", unitCategory = "Force", min = 0.0, allowNegative = false), InputFieldDefinition("mu", "Friction coefficient", min = 0.0, allowNegative = false), InputFieldDefinition("N", "Normal force", canonicalUnit = "N", unitCategory = "Force", min = 0.0, allowNegative = false)),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-centripetal-acceleration",
            title = "Centripetal Acceleration",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Circular motion",
            display = "ac=v^2/r",
            rules = mapOf("ac" to "v^2/r", "v" to "sqrt(ac*r)", "r" to "v^2/ac"),
            fields = listOf(InputFieldDefinition("ac", "Centripetal acceleration", canonicalUnit = "m/s2", unitCategory = "Acceleration", min = 0.0, allowNegative = false), InputFieldDefinition("v", "Speed", canonicalUnit = "m/s", unitCategory = "Speed", min = 0.0, allowNegative = false), InputFieldDefinition("r", "Radius", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-centripetal-force",
            title = "Centripetal Force",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Circular motion",
            display = "Fc=m*v^2/r",
            rules = mapOf("Fc" to "m*v^2/r", "m" to "Fc*r/v^2", "v" to "sqrt(Fc*r/m)", "r" to "m*v^2/Fc"),
            fields = listOf(InputFieldDefinition("Fc", "Centripetal force", canonicalUnit = "N", unitCategory = "Force", min = 0.0, allowNegative = false), InputFieldDefinition("m", "Mass", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("v", "Speed", canonicalUnit = "m/s", unitCategory = "Speed", min = 0.0, allowNegative = false), InputFieldDefinition("r", "Radius", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-gravitation",
            title = "Universal Gravitation",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Gravitation",
            display = "F=G*m1*m2/r^2",
            rules = mapOf("F" to "6.67430e-11*m1*m2/r^2", "m1" to "F*r^2/(6.67430e-11*m2)", "m2" to "F*r^2/(6.67430e-11*m1)", "r" to "sqrt(6.67430e-11*m1*m2/F)"),
            fields = listOf(InputFieldDefinition("F", "Force", canonicalUnit = "N", unitCategory = "Force", min = 0.0, allowNegative = false), InputFieldDefinition("m1", "Mass 1", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("m2", "Mass 2", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("r", "Separation", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-orbital-speed",
            title = "Circular Orbital Speed",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Gravitation",
            display = "v=sqrt(G*M/r)",
            rules = mapOf("v" to "sqrt(6.67430e-11*M/r)", "M" to "v^2*r/6.67430e-11", "r" to "6.67430e-11*M/v^2"),
            fields = listOf(InputFieldDefinition("v", "Orbital speed", canonicalUnit = "m/s", unitCategory = "Speed", min = 0.0, allowNegative = false), InputFieldDefinition("M", "Central mass", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("r", "Orbital radius", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-hooke",
            title = "Hooke's Law",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Elasticity",
            display = "F=k*x",
            rules = mapOf("F" to "k*x", "k" to "F/x", "x" to "F/k"),
            fields = listOf(InputFieldDefinition("F", "Elastic force", canonicalUnit = "N", unitCategory = "Force"), InputFieldDefinition("k", "Spring constant", canonicalUnit = "N/m", min = 0.0, allowNegative = false), InputFieldDefinition("x", "Displacement", canonicalUnit = "m", unitCategory = "Length")),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-spring-energy",
            title = "Elastic Potential Energy",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Elasticity",
            display = "U=k*x^2/2",
            rules = mapOf("U" to "k*x^2/2", "k" to "2*U/x^2", "x" to "sqrt(2*U/k)"),
            fields = listOf(InputFieldDefinition("U", "Elastic energy", canonicalUnit = "J", unitCategory = "Energy", min = 0.0, allowNegative = false), InputFieldDefinition("k", "Spring constant", canonicalUnit = "N/m", min = 0.0, allowNegative = false), InputFieldDefinition("x", "Extension", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-momentum-collision",
            title = "One-Dimensional Momentum Conservation",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Momentum",
            display = "m1*u1+m2*u2=m1*v1+m2*v2",
            rules = mapOf("u1" to "(m1*v1+m2*v2-m2*u2)/m1", "u2" to "(m1*v1+m2*v2-m1*u1)/m2", "v1" to "(m1*u1+m2*u2-m2*v2)/m1", "v2" to "(m1*u1+m2*u2-m1*v1)/m2"),
            fields = listOf(InputFieldDefinition("m1", "Mass 1", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("u1", "Initial velocity 1", canonicalUnit = "m/s", unitCategory = "Speed"), InputFieldDefinition("m2", "Mass 2", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("u2", "Initial velocity 2", canonicalUnit = "m/s", unitCategory = "Speed"), InputFieldDefinition("v1", "Final velocity 1", canonicalUnit = "m/s", unitCategory = "Speed"), InputFieldDefinition("v2", "Final velocity 2", canonicalUnit = "m/s", unitCategory = "Speed")),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-projectile-range",
            title = "Projectile Range",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Projectile motion",
            display = "R=v0^2*sin(2*theta)/g",
            rules = mapOf("R" to "v0^2*sin(2*theta)/g", "v0" to "sqrt(R*g/sin(2*theta))", "g" to "v0^2*sin(2*theta)/R", "theta" to "asin(R*g/v0^2)/2"),
            fields = listOf(InputFieldDefinition("R", "Range", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false), InputFieldDefinition("v0", "Launch speed", canonicalUnit = "m/s", unitCategory = "Speed", min = 0.0, allowNegative = false), InputFieldDefinition("theta", "Launch angle", canonicalUnit = "rad", unitCategory = "Angle"), InputFieldDefinition("g", "Gravity", canonicalUnit = "m/s2", unitCategory = "Acceleration", min = 0.0, allowNegative = false)),
            tags = setOf("grade10", "mechanics"),
            branches = mapOf("theta" to listOf("(pi-asin(R*g/v0^2))/2")),
            symbolic = mapOf("theta" to "theta = 1/2 asin(Rg/v0²) or theta = 1/2(π-asin(Rg/v0²))")
        ),
        formulaTool(
            id = "physics-g10-projectile-height",
            title = "Projectile Maximum Height",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Projectile motion",
            display = "H=v0^2*sin(theta)^2/(2*g)",
            rules = mapOf("H" to "v0^2*sin(theta)^2/(2*g)", "v0" to "sqrt(2*g*H)/abs(sin(theta))", "g" to "v0^2*sin(theta)^2/(2*H)"),
            fields = listOf(InputFieldDefinition("H", "Maximum height", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false), InputFieldDefinition("v0", "Launch speed", canonicalUnit = "m/s", unitCategory = "Speed", min = 0.0, allowNegative = false), InputFieldDefinition("theta", "Launch angle", canonicalUnit = "rad", unitCategory = "Angle"), InputFieldDefinition("g", "Gravity", canonicalUnit = "m/s2", unitCategory = "Acceleration", min = 0.0, allowNegative = false)),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g10-mechanical-efficiency",
            title = "Mechanical Efficiency",
            subject = Subject.PHYSICS,
            category = "Grade 10 Physics",
            topic = "Work and power",
            display = "eta=useful/input*100",
            rules = mapOf("eta" to "useful/input*100", "useful" to "eta*input/100", "input" to "useful*100/eta"),
            fields = listOf(InputFieldDefinition("eta", "Efficiency", canonicalUnit = "%", min = 0.0, max = 100.0, allowNegative = false), InputFieldDefinition("useful", "Useful work/power", min = 0.0, allowNegative = false), InputFieldDefinition("input", "Input work/power", min = 0.0, allowNegative = false)),
            tags = setOf("grade10", "mechanics"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-spring-shm",
            title = "Spring Oscillator Period",
            subject = Subject.PHYSICS,
            category = "Grade 11 Physics",
            topic = "Oscillations",
            display = "T=2*pi*sqrt(m/k)",
            rules = mapOf("T" to "2*pi*sqrt(m/k)", "m" to "k*(T/(2*pi))^2", "k" to "m*(2*pi/T)^2"),
            fields = listOf(InputFieldDefinition("T", "Period", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false), InputFieldDefinition("m", "Mass", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("k", "Spring constant", canonicalUnit = "N/m", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "oscillation"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-pendulum",
            title = "Simple Pendulum Period",
            subject = Subject.PHYSICS,
            category = "Grade 11 Physics",
            topic = "Oscillations",
            display = "T=2*pi*sqrt(L/g)",
            rules = mapOf("T" to "2*pi*sqrt(L/g)", "L" to "g*(T/(2*pi))^2", "g" to "L*(2*pi/T)^2"),
            fields = listOf(InputFieldDefinition("T", "Period", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false), InputFieldDefinition("L", "Length", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false), InputFieldDefinition("g", "Gravity", canonicalUnit = "m/s2", unitCategory = "Acceleration", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "oscillation"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-inductor-energy",
            title = "Inductor Energy",
            subject = Subject.PHYSICS,
            category = "Grade 11 Physics",
            topic = "Electromagnetism",
            display = "U=L*I^2/2",
            rules = mapOf("U" to "L*I^2/2", "L" to "2*U/I^2", "I" to "sqrt(2*U/L)"),
            fields = listOf(InputFieldDefinition("U", "Energy", canonicalUnit = "J", unitCategory = "Energy", min = 0.0, allowNegative = false), InputFieldDefinition("L", "Inductance", canonicalUnit = "H", min = 0.0, allowNegative = false), InputFieldDefinition("I", "Current", canonicalUnit = "A", unitCategory = "Current", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "electricity"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-lc-resonance",
            title = "LC Resonance",
            subject = Subject.PHYSICS,
            category = "Grade 11 Physics",
            topic = "Oscillations",
            display = "f=1/(2*pi*sqrt(L*C))",
            rules = mapOf("f" to "1/(2*pi*sqrt(L*C))", "L" to "1/((2*pi*f)^2*C)", "C" to "1/((2*pi*f)^2*L)"),
            fields = listOf(InputFieldDefinition("f", "Frequency", canonicalUnit = "Hz", unitCategory = "Frequency", min = 0.0, allowNegative = false), InputFieldDefinition("L", "Inductance", canonicalUnit = "H", min = 0.0, allowNegative = false), InputFieldDefinition("C", "Capacitance", canonicalUnit = "F", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "oscillation"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-capacitive-reactance",
            title = "Capacitive Reactance",
            subject = Subject.PHYSICS,
            category = "Grade 11 Physics",
            topic = "AC circuits",
            display = "Xc=1/(2*pi*f*C)",
            rules = mapOf("Xc" to "1/(2*pi*f*C)", "f" to "1/(2*pi*Xc*C)", "C" to "1/(2*pi*f*Xc)"),
            fields = listOf(InputFieldDefinition("Xc", "Capacitive reactance", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false), InputFieldDefinition("f", "Frequency", canonicalUnit = "Hz", unitCategory = "Frequency", min = 0.0, allowNegative = false), InputFieldDefinition("C", "Capacitance", canonicalUnit = "F", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "ac"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-inductive-reactance",
            title = "Inductive Reactance",
            subject = Subject.PHYSICS,
            category = "Grade 11 Physics",
            topic = "AC circuits",
            display = "Xl=2*pi*f*L",
            rules = mapOf("Xl" to "2*pi*f*L", "f" to "Xl/(2*pi*L)", "L" to "Xl/(2*pi*f)"),
            fields = listOf(InputFieldDefinition("Xl", "Inductive reactance", canonicalUnit = "ohm", unitCategory = "Resistance", min = 0.0, allowNegative = false), InputFieldDefinition("f", "Frequency", canonicalUnit = "Hz", unitCategory = "Frequency", min = 0.0, allowNegative = false), InputFieldDefinition("L", "Inductance", canonicalUnit = "H", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "ac"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-rms-voltage",
            title = "Sinusoidal RMS Voltage",
            subject = Subject.PHYSICS,
            category = "Grade 11 Physics",
            topic = "AC circuits",
            display = "Vrms=Vpeak/sqrt(2)",
            rules = mapOf("Vrms" to "Vpeak/sqrt(2)", "Vpeak" to "Vrms*sqrt(2)"),
            fields = listOf(InputFieldDefinition("Vrms", "RMS voltage", canonicalUnit = "V", unitCategory = "Voltage", min = 0.0, allowNegative = false), InputFieldDefinition("Vpeak", "Peak voltage", canonicalUnit = "V", unitCategory = "Voltage", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "ac"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-photoelectric",
            title = "Photoelectric Maximum Kinetic Energy",
            subject = Subject.PHYSICS,
            category = "Advanced Physics",
            topic = "Quantum physics",
            display = "Kmax=h*f-phi",
            rules = mapOf("Kmax" to "6.62607015e-34*f-phi", "f" to "(Kmax+phi)/6.62607015e-34", "phi" to "6.62607015e-34*f-Kmax"),
            fields = listOf(InputFieldDefinition("Kmax", "Maximum kinetic energy", canonicalUnit = "J"), InputFieldDefinition("f", "Frequency", canonicalUnit = "Hz", unitCategory = "Frequency", min = 0.0, allowNegative = false), InputFieldDefinition("phi", "Work function", canonicalUnit = "J", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "advanced", "quantum"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-photon-energy",
            title = "Photon Energy",
            subject = Subject.PHYSICS,
            category = "Advanced Physics",
            topic = "Quantum physics",
            display = "E=h*f",
            rules = mapOf("E" to "6.62607015e-34*f", "f" to "E/6.62607015e-34"),
            fields = listOf(InputFieldDefinition("E", "Photon energy", canonicalUnit = "J", unitCategory = "Energy", min = 0.0, allowNegative = false), InputFieldDefinition("f", "Frequency", canonicalUnit = "Hz", unitCategory = "Frequency", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "advanced", "quantum"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-de-broglie",
            title = "de Broglie Wavelength",
            subject = Subject.PHYSICS,
            category = "Advanced Physics",
            topic = "Quantum physics",
            display = "lambda=h/p",
            rules = mapOf("lambda" to "6.62607015e-34/p", "p" to "6.62607015e-34/lambda"),
            fields = listOf(InputFieldDefinition("lambda", "Wavelength", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false), InputFieldDefinition("p", "Momentum", canonicalUnit = "kg*m/s", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "advanced", "quantum"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-mass-energy",
            title = "Mass–Energy Equivalence",
            subject = Subject.PHYSICS,
            category = "Advanced Physics",
            topic = "Relativity",
            display = "E=m*c^2",
            rules = mapOf("E" to "m*299792458^2", "m" to "E/299792458^2"),
            fields = listOf(InputFieldDefinition("E", "Energy", canonicalUnit = "J", unitCategory = "Energy", min = 0.0, allowNegative = false), InputFieldDefinition("m", "Mass", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "advanced", "relativity"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-radioactive-decay",
            title = "Radioactive Decay",
            subject = Subject.PHYSICS,
            category = "Advanced Physics",
            topic = "Nuclear physics",
            display = "N=N0*exp(-lambda*t)",
            rules = mapOf("N" to "N0*exp(-lambda*t)", "N0" to "N/exp(-lambda*t)", "lambda" to "-ln(N/N0)/t", "t" to "-ln(N/N0)/lambda"),
            fields = listOf(InputFieldDefinition("N", "Remaining nuclei/activity", min = 0.0, allowNegative = false), InputFieldDefinition("N0", "Initial nuclei/activity", min = 0.0, allowNegative = false), InputFieldDefinition("lambda", "Decay constant", canonicalUnit = "1/s", min = 0.0, allowNegative = false), InputFieldDefinition("t", "Time", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "advanced", "nuclear"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-half-life",
            title = "Half-Life and Decay Constant",
            subject = Subject.PHYSICS,
            category = "Advanced Physics",
            topic = "Nuclear physics",
            display = "T_half=ln(2)/lambda",
            rules = mapOf("T_half" to "ln(2)/lambda", "lambda" to "ln(2)/T_half"),
            fields = listOf(InputFieldDefinition("T_half", "Half-life", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false), InputFieldDefinition("lambda", "Decay constant", canonicalUnit = "1/s", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "advanced", "nuclear"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-binding-energy",
            title = "Nuclear Binding Energy from Mass Defect",
            subject = Subject.PHYSICS,
            category = "Advanced Physics",
            topic = "Nuclear physics",
            display = "E=dm*c^2",
            rules = mapOf("E" to "dm*299792458^2", "dm" to "E/299792458^2"),
            fields = listOf(InputFieldDefinition("E", "Binding energy", canonicalUnit = "J", unitCategory = "Energy", min = 0.0, allowNegative = false), InputFieldDefinition("dm", "Mass defect", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "advanced", "nuclear"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "physics-g11-em-wave",
            title = "Electromagnetic Wave Relation",
            subject = Subject.PHYSICS,
            category = "Grade 11 Physics",
            topic = "Electromagnetic waves",
            display = "c=f*lambda",
            rules = mapOf("f" to "299792458/lambda", "lambda" to "299792458/f"),
            fields = listOf(InputFieldDefinition("f", "Frequency", canonicalUnit = "Hz", unitCategory = "Frequency", min = 0.0, allowNegative = false), InputFieldDefinition("lambda", "Wavelength", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf("grade11", "waves"),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "geometry-v4-annulus-area",
            title = "Annulus Area",
            subject = Subject.GEOMETRY,
            category = "Geometry Expansion",
            topic = "Circles",
            display = "A=pi*(R^2-r^2)",
            rules = mapOf("A" to "pi*(R^2-r^2)", "R" to "sqrt(A/pi+r^2)", "r" to "sqrt(R^2-A/pi)"),
            fields = listOf(InputFieldDefinition("A", "Area", canonicalUnit = "m2", unitCategory = "Area", min = 0.0, allowNegative = false), InputFieldDefinition("R", "Outer radius", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false), InputFieldDefinition("r", "Inner radius", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "geometry-v4-pyramid-volume",
            title = "Pyramid Volume",
            subject = Subject.GEOMETRY,
            category = "Geometry Expansion",
            topic = "Solids",
            display = "V=A_base*h/3",
            rules = mapOf("V" to "A_base*h/3", "A_base" to "3*V/h", "h" to "3*V/A_base"),
            fields = listOf(InputFieldDefinition("V", "Volume", canonicalUnit = "m3", unitCategory = "Volume", min = 0.0, allowNegative = false), InputFieldDefinition("A_base", "Base area", canonicalUnit = "m2", unitCategory = "Area", min = 0.0, allowNegative = false), InputFieldDefinition("h", "Height", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "geometry-v4-frustum-volume",
            title = "Conical Frustum Volume",
            subject = Subject.GEOMETRY,
            category = "Geometry Expansion",
            topic = "Solids",
            display = "V=pi*h*(R^2+R*r+r^2)/3",
            rules = mapOf("V" to "pi*h*(R^2+R*r+r^2)/3", "h" to "3*V/(pi*(R^2+R*r+r^2))"),
            fields = listOf(InputFieldDefinition("V", "Volume", canonicalUnit = "m3", unitCategory = "Volume", min = 0.0, allowNegative = false), InputFieldDefinition("h", "Height", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false), InputFieldDefinition("R", "Large radius", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false), InputFieldDefinition("r", "Small radius", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "geometry-v4-sphere-surface-area",
            title = "Sphere Surface Area",
            subject = Subject.GEOMETRY,
            category = "Geometry Expansion",
            topic = "Solids",
            display = "A=4*pi*r^2",
            rules = mapOf("A" to "4*pi*r^2", "r" to "sqrt(A/(4*pi))"),
            fields = listOf(InputFieldDefinition("A", "Surface area", canonicalUnit = "m2", unitCategory = "Area", min = 0.0, allowNegative = false), InputFieldDefinition("r", "Radius", canonicalUnit = "m", unitCategory = "Length", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "chem-v4-molality",
            title = "Molality",
            subject = Subject.CHEMISTRY,
            category = "Chemistry Expansion",
            topic = "Solutions",
            display = "b=n_solute/kg_solvent",
            rules = mapOf("b" to "n/kg", "n" to "b*kg", "kg" to "n/b"),
            fields = listOf(InputFieldDefinition("b", "Molality", canonicalUnit = "mol/kg", min = 0.0, allowNegative = false), InputFieldDefinition("n", "Solute amount", canonicalUnit = "mol", min = 0.0, allowNegative = false), InputFieldDefinition("kg", "Solvent mass", canonicalUnit = "kg", unitCategory = "Mass", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "chem-v4-mass-fraction",
            title = "Mass Fraction",
            subject = Subject.CHEMISTRY,
            category = "Chemistry Expansion",
            topic = "Solutions",
            display = "w=m_solute/m_solution",
            rules = mapOf("w" to "m_solute/m_solution", "m_solute" to "w*m_solution", "m_solution" to "m_solute/w"),
            fields = listOf(InputFieldDefinition("w", "Mass fraction", min = 0.0, max = 1.0, allowNegative = false), InputFieldDefinition("m_solute", "Solute mass", canonicalUnit = "g", unitCategory = "Mass", min = 0.0, allowNegative = false), InputFieldDefinition("m_solution", "Solution mass", canonicalUnit = "g", unitCategory = "Mass", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "chem-v4-percent-yield",
            title = "Percent Yield",
            subject = Subject.CHEMISTRY,
            category = "Chemistry Expansion",
            topic = "Stoichiometry",
            display = "yield=actual/theoretical*100",
            rules = mapOf("yield" to "actual/theoretical*100", "actual" to "yield*theoretical/100", "theoretical" to "actual*100/yield"),
            fields = listOf(InputFieldDefinition("yield", "Percent yield", canonicalUnit = "%", min = 0.0, allowNegative = false), InputFieldDefinition("actual", "Actual yield", min = 0.0, allowNegative = false), InputFieldDefinition("theoretical", "Theoretical yield", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "chem-v4-ph",
            title = "pH from Hydrogen Ion Concentration",
            subject = Subject.CHEMISTRY,
            category = "Chemistry Expansion",
            topic = "Acid-base",
            display = "pH=-log10(H)",
            rules = mapOf("pH" to "-log10(H)", "H" to "10^(-pH)"),
            fields = listOf(InputFieldDefinition("pH", "pH"), InputFieldDefinition("H", "Hydrogen ion concentration", canonicalUnit = "mol/L", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "chem-v4-first-order-half-life",
            title = "First-Order Reaction Half-Life",
            subject = Subject.CHEMISTRY,
            category = "Chemistry Expansion",
            topic = "Kinetics",
            display = "t_half=ln(2)/k",
            rules = mapOf("t_half" to "ln(2)/k", "k" to "ln(2)/t_half"),
            fields = listOf(InputFieldDefinition("t_half", "Half-life", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false), InputFieldDefinition("k", "Rate constant", canonicalUnit = "1/s", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "stats-v4-z-score",
            title = "Z-Score",
            subject = Subject.STATISTICS,
            category = "Statistics Expansion",
            topic = "Standardization",
            display = "z=(x-mu)/sigma",
            rules = mapOf("z" to "(x-mu)/sigma", "x" to "mu+z*sigma", "mu" to "x-z*sigma", "sigma" to "(x-mu)/z"),
            fields = listOf(InputFieldDefinition("z", "Z-score"), InputFieldDefinition("x", "Value"), InputFieldDefinition("mu", "Mean"), InputFieldDefinition("sigma", "Standard deviation", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "stats-v4-standard-error",
            title = "Standard Error of Mean",
            subject = Subject.STATISTICS,
            category = "Statistics Expansion",
            topic = "Sampling",
            display = "SE=sigma/sqrt(n)",
            rules = mapOf("SE" to "sigma/sqrt(n)", "sigma" to "SE*sqrt(n)", "n" to "(sigma/SE)^2"),
            fields = listOf(InputFieldDefinition("SE", "Standard error", min = 0.0, allowNegative = false), InputFieldDefinition("sigma", "Standard deviation", min = 0.0, allowNegative = false), InputFieldDefinition("n", "Sample size", min = 1.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "stats-v4-binomial-mean",
            title = "Binomial Mean",
            subject = Subject.STATISTICS,
            category = "Statistics Expansion",
            topic = "Probability",
            display = "mu=n*p",
            rules = mapOf("mu" to "n*p", "n" to "mu/p", "p" to "mu/n"),
            fields = listOf(InputFieldDefinition("mu", "Mean", min = 0.0, allowNegative = false), InputFieldDefinition("n", "Trials", min = 0.0, allowNegative = false), InputFieldDefinition("p", "Success probability", min = 0.0, max = 1.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "finance-v4-cagr",
            title = "Compound Annual Growth Rate",
            subject = Subject.FINANCE,
            category = "Finance Expansion",
            topic = "Growth",
            display = "CAGR=(end/start)^(1/years)-1",
            rules = mapOf("CAGR" to "(end/start)^(1/years)-1", "end" to "start*(1+CAGR)^years", "start" to "end/(1+CAGR)^years"),
            fields = listOf(InputFieldDefinition("CAGR", "CAGR"), InputFieldDefinition("end", "Ending value", min = 0.0, allowNegative = false), InputFieldDefinition("start", "Starting value", min = 0.0, allowNegative = false), InputFieldDefinition("years", "Years", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "finance-v4-future-value-annuity",
            title = "Future Value of Ordinary Annuity",
            subject = Subject.FINANCE,
            category = "Finance Expansion",
            topic = "Annuities",
            display = "FV=PMT*((1+r)^n-1)/r",
            rules = mapOf("FV" to "PMT*((1+r)^n-1)/r", "PMT" to "FV*r/((1+r)^n-1)"),
            fields = listOf(InputFieldDefinition("FV", "Future value"), InputFieldDefinition("PMT", "Periodic payment"), InputFieldDefinition("r", "Rate per period"), InputFieldDefinition("n", "Periods", min = 1.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "finance-v4-present-value",
            title = "Present Value",
            subject = Subject.FINANCE,
            category = "Finance Expansion",
            topic = "Time value",
            display = "PV=FV/(1+r)^n",
            rules = mapOf("PV" to "FV/(1+r)^n", "FV" to "PV*(1+r)^n", "r" to "(FV/PV)^(1/n)-1"),
            fields = listOf(InputFieldDefinition("PV", "Present value"), InputFieldDefinition("FV", "Future value"), InputFieldDefinition("r", "Rate per period"), InputFieldDefinition("n", "Periods", min = 1.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "computer-v4-transfer-time",
            title = "Data Transfer Time",
            subject = Subject.COMPUTER,
            category = "Computer Expansion",
            topic = "Networking",
            display = "time=bytes*8/bps",
            rules = mapOf("time" to "bytes*8/bps", "bytes" to "time*bps/8", "bps" to "bytes*8/time"),
            fields = listOf(InputFieldDefinition("time", "Transfer time", canonicalUnit = "s", unitCategory = "Time", min = 0.0, allowNegative = false), InputFieldDefinition("bytes", "Data size", canonicalUnit = "byte", unitCategory = "Data / Storage", min = 0.0, allowNegative = false), InputFieldDefinition("bps", "Bit rate", canonicalUnit = "bit/s", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "computer-v4-storage-overhead",
            title = "Storage Overhead",
            subject = Subject.COMPUTER,
            category = "Computer Expansion",
            topic = "Storage",
            display = "total=payload*(1+overhead)",
            rules = mapOf("total" to "payload*(1+overhead)", "payload" to "total/(1+overhead)", "overhead" to "total/payload-1"),
            fields = listOf(InputFieldDefinition("total", "Total storage", canonicalUnit = "byte", unitCategory = "Data / Storage", min = 0.0, allowNegative = false), InputFieldDefinition("payload", "Payload storage", canonicalUnit = "byte", unitCategory = "Data / Storage", min = 0.0, allowNegative = false), InputFieldDefinition("overhead", "Overhead fraction", min = 0.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "computer-v4-pixel-buffer",
            title = "Pixel Buffer Size",
            subject = Subject.COMPUTER,
            category = "Computer Expansion",
            topic = "Graphics",
            display = "bytes=width*height*bpp/8",
            rules = mapOf("bytes" to "width*height*bpp/8", "width" to "bytes*8/(height*bpp)", "height" to "bytes*8/(width*bpp)", "bpp" to "bytes*8/(width*height)"),
            fields = listOf(InputFieldDefinition("bytes", "Buffer bytes", canonicalUnit = "byte", unitCategory = "Data / Storage", min = 0.0, allowNegative = false), InputFieldDefinition("width", "Width pixels", min = 1.0, allowNegative = false), InputFieldDefinition("height", "Height pixels", min = 1.0, allowNegative = false), InputFieldDefinition("bpp", "Bits per pixel", min = 1.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "date-v4-duration-hours",
            title = "Duration Hours",
            subject = Subject.DATE_TIME,
            category = "Date / Time Expansion",
            topic = "Durations",
            display = "hours=seconds/3600",
            rules = mapOf("hours" to "seconds/3600", "seconds" to "hours*3600"),
            fields = listOf(InputFieldDefinition("hours", "Hours", canonicalUnit = "h", unitCategory = "Time"), InputFieldDefinition("seconds", "Seconds", canonicalUnit = "s", unitCategory = "Time")),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "date-v4-epoch-seconds",
            title = "Epoch Milliseconds / Seconds",
            subject = Subject.DATE_TIME,
            category = "Date / Time Expansion",
            topic = "Epoch",
            display = "milliseconds=seconds*1000",
            rules = mapOf("milliseconds" to "seconds*1000", "seconds" to "milliseconds/1000"),
            fields = listOf(InputFieldDefinition("milliseconds", "Epoch milliseconds"), InputFieldDefinition("seconds", "Epoch seconds")),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "text-v4-reading-time",
            title = "Reading Time",
            subject = Subject.TEXT_LANGUAGE,
            category = "Text Expansion",
            topic = "Reading metrics",
            display = "minutes=words/wpm",
            rules = mapOf("minutes" to "words/wpm", "words" to "minutes*wpm", "wpm" to "words/minutes"),
            fields = listOf(InputFieldDefinition("minutes", "Minutes", canonicalUnit = "min", unitCategory = "Time", min = 0.0, allowNegative = false), InputFieldDefinition("words", "Word count", min = 0.0, allowNegative = false), InputFieldDefinition("wpm", "Words per minute", min = 1.0, allowNegative = false)),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "math-v4-exponential-growth",
            title = "Exponential Growth",
            subject = Subject.MATH,
            category = "Math Expansion",
            topic = "Exponential",
            display = "final=initial*(1+r)^t",
            rules = mapOf("final" to "initial*(1+r)^t", "initial" to "final/(1+r)^t", "r" to "(final/initial)^(1/t)-1"),
            fields = listOf(InputFieldDefinition("final", "Final value"), InputFieldDefinition("initial", "Initial value"), InputFieldDefinition("r", "Rate"), InputFieldDefinition("t", "Periods")),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        ),
        formulaTool(
            id = "math-v4-distance-3d",
            title = "3D Distance",
            subject = Subject.MATH,
            category = "Math Expansion",
            topic = "Coordinate geometry",
            display = "d=sqrt(dx^2+dy^2+dz^2)",
            rules = mapOf("d" to "sqrt(dx^2+dy^2+dz^2)", "dx" to "sqrt(d^2-dy^2-dz^2)", "dy" to "sqrt(d^2-dx^2-dz^2)", "dz" to "sqrt(d^2-dx^2-dy^2)"),
            fields = listOf(InputFieldDefinition("d", "Distance", min = 0.0, allowNegative = false), InputFieldDefinition("dx", "Delta x"), InputFieldDefinition("dy", "Delta y"), InputFieldDefinition("dz", "Delta z")),
            tags = setOf(),
            branches = emptyMap(),
            symbolic = mapOf()
        )
    ).also { tools ->
        require(tools.size == EXPECTED_ADDITIONS) { "V4 catalog size drift: ${tools.size}" }
        require(tools.map { it.id }.toSet().size == tools.size) { "V4 tool ids must be unique" }
    }

    private fun formulaTool(
        id: String,
        title: String,
        subject: Subject,
        category: String,
        topic: String,
        display: String,
        rules: Map<String, String>,
        fields: List<InputFieldDefinition>,
        tags: Set<String> = emptySet(),
        branches: Map<String, List<String>> = emptyMap(),
        symbolic: Map<String, String> = emptyMap()
    ): ToolDefinition {
        val targets = (rules.keys + branches.keys).distinct()
        require(targets.isNotEmpty()) { "$id must expose at least one solve target" }
        val fieldIds = fields.map { it.id }.toSet()
        require(targets.all { it in fieldIds }) { "$id solve target missing from input schema" }
        return ToolDefinition(
            id = id,
            title = title,
            subject = subject,
            category = category,
            topic = topic,
            description = "Deterministic V4 solver for $display. Missing values are never guessed.",
            aliases = setOf(title.lowercase(), display.lowercase()),
            keywords = tags,
            tags = tags,
            environmentFamily = when (subject) {
                Subject.GEOMETRY -> EnvironmentFamily.GeometryTool
                Subject.FINANCE -> EnvironmentFamily.FinanceTool
                Subject.DATE_TIME -> EnvironmentFamily.DateTimeTool
                Subject.TEXT_LANGUAGE -> EnvironmentFamily.TextAnalyzer
                else -> EnvironmentFamily.FormulaSolver
            },
            executorKind = ToolExecutorKind.FORMULA,
            inputSchema = fields,
            outputSchema = targets.map { OutputFieldDefinition(it, it, OutputKind.NUMBER, fields.firstOrNull { f -> f.id == it }?.canonicalUnit) },
            formulaDefinition = FormulaDefinition(
                display = display,
                solveRules = rules,
                notes = "V4 deterministic relation; explicit target selection supported.",
                solveBranches = branches,
                symbolicByTarget = symbolic
            ),
            validationRules = listOf("All declared domain constraints are enforced; required values may not be guessed."),
            relatedToolIds = emptySet(),
            supportsWidget = false,
            supportedWidgetSizes = emptySet(),
            supportsFloatingCompactMode = false,
            offlinePolicy = OfflinePolicy.OFFLINE_FULL,
            liveDataPolicy = LiveDataPolicy.NONE,
            schemaVersion = 4
        )
    }
}
