import { PGlite } from '@electric-sql/pglite'
import { pgcrypto } from '@electric-sql/pglite/contrib/pgcrypto'
import { readFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterEach, describe, expect, it } from 'vitest'

const HERE = dirname(fileURLToPath(import.meta.url))
const DB_DIR = join(HERE, '..', 'db')
const MIGRATIONS = [
  'migration-100-vh-part1-foundation.sql','migration-101-vh-part1-hardening.sql',
  'migration-102-vh-part1-service-only.sql','migration-103-vh-part1-index-hardening.sql',
  'migration-104-vh-part2-knowledge-core.sql','migration-105-vh-part2-integrity-hardening.sql',
  'migration-106-vh-part2-library-query.sql','migration-107-vh-part2-job-state-sync.sql',
  'migration-108-vh-part2-scoped-notebook-retrieval.sql','migration-109-vh-part2-research-owner-guards.sql',
  'migration-110-vh-part2-trash-metadata-delete.sql','migration-111-vh-part2-fk-index-hardening.sql',
  'migration-112-vh-part2-library-keyset-indexes.sql','migration-113-vh-part2-library-page-first.sql',
  'migration-114-vh-part2-library-search-hits.sql',
]
const A = '11111111-1111-4111-8111-111111111111'
const B = '22222222-2222-4222-8222-222222222222'
let opened: PGlite[] = []
afterEach(async () => { for (const db of opened.splice(0)) await db.close() })

async function freshDb() {
  const db = await PGlite.create({ extensions: { pgcrypto } })
  opened.push(db)
  await db.exec(`
    create extension if not exists pgcrypto;
    create schema if not exists storage;
    create table if not exists storage.buckets(id text primary key,name text not null,public boolean not null default false,file_size_limit bigint);
    do $$ begin if not exists (select 1 from pg_roles where rolname='service_role') then create role service_role; end if; end $$;
    do $$ begin if not exists (select 1 from pg_roles where rolname='authenticated') then create role authenticated; end if; end $$;
    do $$ begin if not exists (select 1 from pg_roles where rolname='anon') then create role anon; end if; end $$;
  `)
  for (const file of MIGRATIONS) await db.exec(readFileSync(join(DB_DIR, file), 'utf8'))
  await db.exec(`insert into public.vh_accounts(id,email) values ('${A}','part2-a@example.invalid'),('${B}','part2-b@example.invalid')`)
  return db
}

function sha(seed: string) { return createHash('sha256').update(seed).digest('hex') }
async function asset(db: PGlite, account: string, opts: { id?: string; title?: string; bytes?: number; hashSeed?: string; assetClass?: 'file'|'image'|'web'|'text'; kind?: 'pdf'|'document'|'pptx'|'text'|'spreadsheet'|'epub'|'image'|'audio'|'video'|'web'|'pasted'|'scanned'|'other'; status?: 'UPLOADED'|'QUEUED'|'PROCESSING'|'READY'|'FAILED'|'UNSUPPORTED'; extraction?: 'PENDING'|'PROCESSING'|'READY'|'FAILED'|'UNSUPPORTED'|'NOT_REQUIRED'; origin?: string; favorite?: boolean; createdOffset?: number } = {}) {
  const id = opts.id ?? crypto.randomUUID()
  const title = opts.title ?? `Asset ${id.slice(0, 6)}`
  await db.query(`insert into public.vh_library_assets(id,account_id,original_filename,display_title,declared_mime,detected_mime,source_kind,asset_class,original_size_bytes,origin_surface,content_sha256,processing_status,extraction_status,favorite,created_at,updated_at) values ($1,$2,$3,$4,'application/octet-stream','application/octet-stream',$5,$6,$7,$8,$9,$10,$11,$12,now()+($13::text||' seconds')::interval,now()+($13::text||' seconds')::interval)`, [id,account,`${title}.bin`,title,opts.kind ?? 'other',opts.assetClass ?? 'file',opts.bytes ?? 1,opts.origin ?? 'test',sha(opts.hashSeed ?? id),opts.status ?? 'READY',opts.extraction ?? 'READY',opts.favorite ?? false,opts.createdOffset ?? 0])
  return id
}
async function project(db: PGlite, account=A, name='Project') { return (await db.query<{id:string}>(`insert into public.vh_projects(account_id,name) values ($1,$2) returning id`,[account,name])).rows[0]!.id }
async function notebook(db: PGlite, account=A, name='Notebook') { return (await db.query<{id:string}>(`insert into public.vh_notebooks(account_id,name) values ($1,$2) returning id`,[account,name])).rows[0]!.id }

describe('Part 2 canonical persistence and acceptance contracts', () => {
  it('applies migrations 100-114 and keeps canonical Part 2 tables service-only with RLS', async () => {
    const db=await freshDb(); const expected=['vh_projects','vh_library_assets','vh_asset_usages','vh_ingest_sessions','vh_project_references','vh_library_tags','vh_library_asset_tags','vh_library_collections','vh_collection_assets','vh_notebooks','vh_project_notebooks','vh_notebook_sources','vh_source_chunks','vh_research_sessions','vh_research_candidates']
    const tables=await db.query<{table_name:string;rls:boolean}>(`select c.relname table_name,c.relrowsecurity rls from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=any($1::text[]) order by c.relname`,[expected]); expect(tables.rows).toHaveLength(expected.length); expect(tables.rows.every(r=>r.rls)).toBe(true)
    await db.exec('set role anon'); try { await expect(db.query(`select * from public.vh_projects`)).rejects.toThrow() } finally { await db.exec('reset role') }
    await db.exec('set role authenticated'); try { await expect(db.query(`select * from public.vh_library_assets`)).rejects.toThrow() } finally { await db.exec('reset role') }
  })

  it('enforces Project 20-reference and exact 50 MiB caps while duplicate Add remains idempotent', async () => {
    const db=await freshDb(), pCount=await project(db,A,'Count cap'), ids:string[]=[]
    for(let i=0;i<21;i++) ids.push(await asset(db,A,{hashSeed:`ref-seed-${i}`,title:`Ref-${i}`,bytes:1}))
    for(let i=0;i<20;i++) await db.query(`select public.vh_add_project_reference($1,$2,$3)`,[A,pCount,ids[i]])
    const first=await db.query<{id:string}>(`select public.vh_add_project_reference($1,$2,$3) id`,[A,pCount,ids[0]]), again=await db.query<{id:string}>(`select public.vh_add_project_reference($1,$2,$3) id`,[A,pCount,ids[0]]); expect(again.rows[0]!.id).toBe(first.rows[0]!.id)
    await expect(db.query(`select public.vh_add_project_reference($1,$2,$3)`,[A,pCount,ids[20]])).rejects.toThrow(/project_reference_count_exceeded/)
    const pBytes=await project(db,A,'Bytes cap'), exact=await asset(db,A,{hashSeed:'exact50',title:'Exact50',bytes:50*1024*1024}), plus=await asset(db,A,{hashSeed:'plus1',title:'Plus1',bytes:1}); await db.query(`select public.vh_add_project_reference($1,$2,$3)`,[A,pBytes,exact]); await expect(db.query(`select public.vh_add_project_reference($1,$2,$3)`,[A,pBytes,plus])).rejects.toThrow(/project_reference_bytes_exceeded/)
    await db.query(`delete from public.vh_project_references where account_id=$1 and project_id=$2 and asset_id=$3`,[A,pBytes,exact]); expect((await db.query<{n:number}>(`select count(*)::int n from public.vh_library_assets where id=$1`,[exact])).rows[0]!.n).toBe(1)
  })

  it('keeps Library dedup owner-scoped and usage contexts idempotent without cross-owner reuse', async () => {
    const db=await freshDb(); const idA=await asset(db,A,{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',hashSeed:'same-content',title:'Dedup A',bytes:100}); await expect(asset(db,A,{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaab',hashSeed:'same-content',title:'Duplicate A',bytes:100})).rejects.toThrow(); const idB=await asset(db,B,{id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',hashSeed:'same-content',title:'Same Hash B',bytes:100}); expect(idB).not.toBe(idA)
    const context='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaac'; await db.query(`insert into public.vh_asset_usages(account_id,asset_id,origin_surface,context_kind,context_id) values ($1,$2,'project','project',$3) on conflict do nothing`,[A,idA,context]); await db.query(`insert into public.vh_asset_usages(account_id,asset_id,origin_surface,context_kind,context_id) values ($1,$2,'project','project',$3) on conflict do nothing`,[A,idA,context]); expect((await db.query<{n:number}>(`select count(*)::int n from public.vh_asset_usages where account_id=$1 and asset_id=$2`,[A,idA])).rows[0]!.n).toBe(1); await expect(db.query(`insert into public.vh_asset_usages(account_id,asset_id,origin_surface) values ($1,$2,'bad')`,[A,idB])).rejects.toThrow()
  })

  it('enforces frozen 900 MiB warning policy and exact 1 GiB hard quota', async () => {
    const db=await freshDb(); const policy=await db.query<{hard:string;warning:string}>(`select hard_bytes::text hard,warning_bytes::text warning from public.vh_quota_policies where policy_key='library.storage'`); expect(policy.rows[0]).toEqual({hard:'1073741824',warning:'943718400'}); await db.query(`select public.vh_reserve_quota($1,'library',$2,$3)`,[A,943718400,1073741824]); await db.query(`select public.vh_reserve_quota($1,'library',$2,$3)`,[A,130023424,1073741824]); await expect(db.query(`select public.vh_reserve_quota($1,'library',1,$2)`,[A,1073741824])).rejects.toThrow(/quota_exceeded/)
  })

  it('supports Tags and file/image-only Collections with owner-safe relationships', async () => {
    const db=await freshDb(), file=await asset(db,A,{hashSeed:'file',assetClass:'file',title:'File'}), image=await asset(db,A,{hashSeed:'image',assetClass:'image',kind:'image',title:'Image'}), web=await asset(db,A,{hashSeed:'web',assetClass:'web',kind:'web',title:'Web'}); const collection=(await db.query<{id:string}>(`insert into public.vh_library_collections(account_id,name) values ($1,'C1') returning id`,[A])).rows[0]!.id; await db.query(`select public.vh_add_collection_asset($1,$2,$3,10)`,[A,collection,file]); await db.query(`select public.vh_add_collection_asset($1,$2,$3,20)`,[A,collection,image]); await expect(db.query(`select public.vh_add_collection_asset($1,$2,$3,30)`,[A,collection,web])).rejects.toThrow(/collection_asset_type_not_allowed/)
    const tag=(await db.query<{id:string}>(`insert into public.vh_library_tags(account_id,name,normalized_name) values ($1,' Physics ','physics') returning id`,[A])).rows[0]!.id; await expect(db.query(`insert into public.vh_library_tags(account_id,name,normalized_name) values ($1,'PHYSICS','physics')`,[A])).rejects.toThrow(); await db.query(`insert into public.vh_library_asset_tags(account_id,asset_id,tag_id) values ($1,$2,$3)`,[A,file,tag]); await expect(db.query(`insert into public.vh_library_asset_tags(account_id,asset_id,tag_id) values ($1,$2,$3)`,[B,file,tag])).rejects.toThrow()
  })

  it('returns deterministic Library keyset pages and composable owner-scoped filters/search', async () => {
    const db=await freshDb(), p=await project(db,A,'Physics Project'), n=await notebook(db,A,'Notebook'), tag=(await db.query<{id:string}>(`insert into public.vh_library_tags(account_id,name,normalized_name) values ($1,'Physics','physics') returning id`,[A])).rows[0]!.id, coll=(await db.query<{id:string}>(`insert into public.vh_library_collections(account_id,name) values ($1,'Collection') returning id`,[A])).rows[0]!.id, ids:string[]=[]
    for(let i=0;i<8;i++) ids.push(await asset(db,A,{id:`aaaaaaaa-aaaa-4aaa-8aaa-${String(i+1).padStart(12,'0')}`,hashSeed:`query-${i}`,title:i===3?'Quantum Physics Notes':`Asset ${i}`,bytes:100+i,favorite:i===3||i%2===0,createdOffset:i})); await asset(db,B,{hashSeed:'foreign-quantum',title:'Quantum Physics Foreign',createdOffset:99}); await db.query(`select public.vh_add_project_reference($1,$2,$3)`,[A,p,ids[3]]); await db.query(`select public.vh_add_notebook_source($1,$2,$3,10,1000000,'library','{}')`,[A,n,ids[3]]); await db.query(`insert into public.vh_library_asset_tags(account_id,asset_id,tag_id) values ($1,$2,$3)`,[A,ids[3],tag]); await db.query(`select public.vh_add_collection_asset($1,$2,$3,0)`,[A,coll,ids[3]]); await db.query(`insert into public.vh_source_chunks(account_id,asset_id,source_revision,chunk_index,content,locator,text_range,content_hash,extraction_version) values ($1,$2,1,0,'quantum entanglement evidence','{"page":4}','{"start":0,"end":29}',$3,'v1')`,[A,ids[3],sha('quantum-chunk')])
    const page1=await db.query<any>(`select * from public.vh_query_library_assets(p_account_id=>$1,p_sort=>'created',p_dir=>'asc',p_limit=>3)`,[A]); expect(page1.rows).toHaveLength(3); const last=page1.rows[2]!; const page2=await db.query<any>(`select * from public.vh_query_library_assets(p_account_id=>$1,p_sort=>'created',p_dir=>'asc',p_cursor_ts=>$2,p_cursor_id=>$3,p_limit=>3)`,[A,last.sort_ts,last.id]); expect(new Set([...page1.rows,...page2.rows].map(r=>r.id)).size).toBe(6)
    const filtered=await db.query<any>(`select * from public.vh_query_library_assets(p_account_id=>$1,p_project_id=>$2,p_notebook_id=>$3,p_tag_ids=>array[$4]::uuid[],p_collection_id=>$5,p_favorite=>true,p_linked=>true,p_q=>'quantum',p_sort=>'created',p_dir=>'desc',p_limit=>40)`,[A,p,n,tag,coll]); expect(filtered.rows.map(r=>r.id)).toEqual([ids[3]]); expect(filtered.rows.find(r=>r.display_title==='Quantum Physics Foreign')).toBeUndefined()
  })

  it('enforces Notebook quotas, many-to-many Project links, idempotent sources and cross-owner isolation', async () => {
    const db=await freshDb(), p1=await project(db,A,'P1'), p2=await project(db,A,'P2'), n=await notebook(db,A,'N'), a1=await asset(db,A,{hashSeed:'a1',bytes:5,title:'A1'}), a2=await asset(db,A,{hashSeed:'a2',bytes:6,title:'A2'}), foreign=await asset(db,B,{hashSeed:'foreign',bytes:1,title:'Foreign'}); const s1=await db.query<{id:string}>(`select public.vh_add_notebook_source($1,$2,$3,1,10,'library','{}') id`,[A,n,a1]), again=await db.query<{id:string}>(`select public.vh_add_notebook_source($1,$2,$3,1,10,'research','{"candidate":"x"}') id`,[A,n,a1]); expect(again.rows[0]!.id).toBe(s1.rows[0]!.id); await expect(db.query(`select public.vh_add_notebook_source($1,$2,$3,1,10,'library','{}')`,[A,n,a2])).rejects.toThrow(/notebook_source_count_exceeded/); await expect(db.query(`select public.vh_add_notebook_source($1,$2,$3,10,100,'library','{}')`,[A,n,foreign])).rejects.toThrow(/asset_not_found/)
    await db.query(`insert into public.vh_project_notebooks(account_id,project_id,notebook_id) values ($1,$2,$3) on conflict do nothing`,[A,p1,n]); await db.query(`insert into public.vh_project_notebooks(account_id,project_id,notebook_id) values ($1,$2,$3) on conflict do nothing`,[A,p2,n]); expect((await db.query<{n:number}>(`select count(*)::int n from public.vh_project_notebooks where notebook_id=$1`,[n])).rows[0]!.n).toBe(2); await db.query(`delete from public.vh_project_notebooks where account_id=$1 and project_id=$2 and notebook_id=$3`,[A,p1,n]); expect((await db.query<{n:number}>(`select count(*)::int n from public.vh_notebooks where id=$1`,[n])).rows[0]!.n).toBe(1)
  })

  it('scopes grounded Notebook and Project retrieval to enabled linked owner sources with exact provenance', async () => {
    const db=await freshDb(), p=await project(db,A,'Grounded Project'), n=await notebook(db,A,'Grounded Notebook'); await db.query(`insert into public.vh_project_notebooks(account_id,project_id,notebook_id) values ($1,$2,$3)`,[A,p,n]); const enabled=await asset(db,A,{hashSeed:'enabled',title:'Enabled'}), disabled=await asset(db,A,{hashSeed:'disabled',title:'Disabled'}), foreign=await asset(db,B,{hashSeed:'foreign-source',title:'Foreign'}); await db.query(`select public.vh_add_notebook_source($1,$2,$3,10,100000,'library','{}')`,[A,n,enabled]); const s2=(await db.query<{id:string}>(`select public.vh_add_notebook_source($1,$2,$3,10,100000,'library','{}') id`,[A,n,disabled])).rows[0]!.id; await db.query(`update public.vh_notebook_sources set enabled=false where id=$1`,[s2])
    await db.query(`insert into public.vh_source_chunks(account_id,asset_id,source_revision,chunk_index,content,locator,text_range,content_hash,extraction_version) values ($1,$2,1,0,'alpha grounded evidence','{"page":7}','{"start":0,"end":23}',$3,'extract-v1'),($1,$4,1,0,'alpha disabled evidence','{"page":8}','{"start":0,"end":23}',$5,'extract-v1'),($6,$7,1,0,'alpha foreign evidence','{"page":9}','{"start":0,"end":22}',$8,'extract-v1')`,[A,enabled,sha('enabled-chunk'),disabled,sha('disabled-chunk'),B,foreign,sha('foreign-chunk')]); const hits=await db.query<any>(`select * from public.vh_search_notebook_chunks_scoped($1,$2,'alpha',null,12)`,[A,n]); expect(hits.rows).toHaveLength(1); expect(hits.rows[0]).toMatchObject({asset_id:enabled,chunk_index:0,locator:{page:7},content_hash:sha('enabled-chunk'),extraction_version:'extract-v1'}); expect(Number(hits.rows[0].source_revision)).toBe(1); expect((await db.query<any>(`select * from public.vh_search_notebook_chunks_scoped($1,$2,'alpha',array[$3]::uuid[],12)`,[A,n,disabled])).rows).toHaveLength(0); expect((await db.query<any>(`select * from public.vh_search_project_chunks($1,$2,'alpha',12)`,[A,p])).rows.map(r=>r.asset_id)).toEqual([enabled])
  })

  it('keeps Research candidates untrusted until explicit Add and enforces accepted asset/job ownership', async () => {
    const db=await freshDb(), n=await notebook(db,A,'Research'), session=(await db.query<{id:string}>(`insert into public.vh_research_sessions(account_id,notebook_id,kind,query,plan,status) values ($1,$2,'fast','quantum','{"steps":["search"]}','review') returning id`,[A,n])).rows[0]!.id, candidate=(await db.query<{id:string}>(`insert into public.vh_research_candidates(account_id,research_session_id,source_url,source_identity_hash,title,fetch_status,provenance) values ($1,$2,'https://example.com/source',$3,'Candidate','candidate','{"provider":"test"}') returning id`,[A,session,sha('candidate')])).rows[0]!.id; expect((await db.query<any>(`select accepted_asset_id,fetch_status from public.vh_research_candidates where id=$1`,[candidate])).rows[0]).toEqual({accepted_asset_id:null,fetch_status:'candidate'})
    const foreignAsset=await asset(db,B,{hashSeed:'foreign-accepted',title:'Foreign accepted'}); await expect(db.query(`update public.vh_research_candidates set accepted_asset_id=$1 where id=$2`,[foreignAsset,candidate])).rejects.toThrow(/research_candidate_asset_owner_mismatch/); const foreignJob=(await db.query<{id:string}>(`insert into public.vh_jobs(account_id,kind) values ($1,'part2.research.fast') returning id`,[B])).rows[0]!.id; await expect(db.query(`update public.vh_research_sessions set job_id=$1 where id=$2`,[foreignJob,session])).rejects.toThrow(/research_job_owner_mismatch/)
    const accepted=await asset(db,A,{hashSeed:'accepted',title:'Accepted'}); await db.query(`update public.vh_research_candidates set accepted_asset_id=$1,fetch_status='verified' where id=$2`,[accepted,candidate]); await db.query(`select public.vh_add_notebook_source($1,$2,$3,20,1000000,'research',$4::jsonb)`,[A,n,accepted,JSON.stringify({candidateId:candidate,sourceUrl:'https://example.com/source'})]); const link=await db.query<any>(`select added_via,discovery_provenance from public.vh_notebook_sources where notebook_id=$1 and asset_id=$2`,[n,accepted]); expect(link.rows[0].added_via).toBe('research'); expect(link.rows[0].discovery_provenance.candidateId).toBe(candidate)
  })

  it('synchronizes durable source/research failures and deletes partial current-revision chunks', async () => {
    const db=await freshDb(), n=await notebook(db,A,'Job Sync'), a=await asset(db,A,{hashSeed:'processing',title:'Processing',status:'PROCESSING',extraction:'PROCESSING'}); await db.query(`insert into public.vh_source_chunks(account_id,asset_id,source_revision,chunk_index,content,content_hash,extraction_version) values ($1,$2,1,0,'partial',$3,'v1')`,[A,a,sha('partial')]); const job=(await db.query<{id:string}>(`insert into public.vh_jobs(account_id,kind,payload,state) values ($1,'part2.source.process',$2::jsonb,'running') returning id`,[A,JSON.stringify({assetId:a})])).rows[0]!.id; await db.query(`update public.vh_jobs set state='failed' where id=$1`,[job]); expect((await db.query<any>(`select processing_status,extraction_status,safe_failure_code from public.vh_library_assets where id=$1`,[a])).rows[0]).toEqual({processing_status:'FAILED',extraction_status:'FAILED',safe_failure_code:'SOURCE_PROCESS_FAILED'}); expect((await db.query<{n:number}>(`select count(*)::int n from public.vh_source_chunks where asset_id=$1`,[a])).rows[0]!.n).toBe(0)
    const session=(await db.query<{id:string}>(`insert into public.vh_research_sessions(account_id,notebook_id,kind,query,status) values ($1,$2,'deep','deep question','running') returning id`,[A,n])).rows[0]!.id, rjob=(await db.query<{id:string}>(`insert into public.vh_jobs(account_id,kind,payload,state) values ($1,'part2.research.deep',$2::jsonb,'running') returning id`,[A,JSON.stringify({sessionId:session})])).rows[0]!.id; await db.query(`update public.vh_jobs set state='retry' where id=$1`,[rjob]); expect((await db.query<any>(`select status,safe_error_code from public.vh_research_sessions where id=$1`,[session])).rows[0]).toEqual({status:'queued',safe_error_code:'RESEARCH_RETRY'}); await db.query(`update public.vh_research_sessions set status='running' where id=$1`,[session]); await db.query(`update public.vh_jobs set state='failed' where id=$1`,[rjob]); expect((await db.query<any>(`select status,safe_error_code,(finished_at is not null) finished from public.vh_research_sessions where id=$1`,[session])).rows[0]).toEqual({status:'failed',safe_error_code:'RESEARCH_FAILED',finished:true})
  })

  it('permanently deletes trashed metadata with relationship cleanup while preserving Library assets for container deletion', async () => {
    const db=await freshDb(), p=await project(db,A,'Trash P'), n=await notebook(db,A,'Trash N'), c=(await db.query<{id:string}>(`insert into public.vh_library_collections(account_id,name) values ($1,'Trash C') returning id`,[A])).rows[0]!.id, storage=(await db.query<{id:string}>(`insert into public.vh_storage_objects(account_id,bucket,object_path,kind,state,size_bytes) values ($1,'vh-library',$2,'library','ready',12) returning id`,[A,`${A}/trash/original`])).rows[0]!.id, a='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaee'; await db.query(`insert into public.vh_library_assets(id,account_id,storage_object_id,original_filename,display_title,source_kind,asset_class,original_size_bytes,origin_surface,content_sha256,processing_status,extraction_status) values ($1,$2,$3,'trash.bin','Trash asset','other','file',12,'test',$4,'READY','READY')`,[a,A,storage,sha('trash-asset')]); await db.query(`select public.vh_add_project_reference($1,$2,$3)`,[A,p,a]); await db.query(`select public.vh_add_notebook_source($1,$2,$3,20,1000000,'library','{}')`,[A,n,a]); await db.query(`select public.vh_add_collection_asset($1,$2,$3,0)`,[A,c,a]); await db.query(`insert into public.vh_source_chunks(account_id,asset_id,source_revision,chunk_index,content,content_hash,extraction_version) values ($1,$2,1,0,'trash chunk',$3,'v1')`,[A,a,sha('trash-chunk')]); await db.query(`update public.vh_library_assets set trashed_at=now(),purge_after=now()+interval '30 days' where id=$1`,[a]); await db.query(`update public.vh_storage_objects set state='trashed',trashed_at=now(),purge_after=now()+interval '30 days' where id=$1`,[storage]); expect((await db.query<{ok:boolean}>(`select public.vh_delete_part2_metadata($1,'asset',$2) ok`,[A,a])).rows[0]!.ok).toBe(true)
    expect((await db.query<{n:number}>(`select count(*)::int n from public.vh_library_assets where id=$1`,[a])).rows[0]!.n).toBe(0); expect((await db.query<{n:number}>(`select count(*)::int n from public.vh_project_references where asset_id=$1`,[a])).rows[0]!.n).toBe(0); expect((await db.query<{n:number}>(`select count(*)::int n from public.vh_notebook_sources where asset_id=$1`,[a])).rows[0]!.n).toBe(0); expect((await db.query<{n:number}>(`select count(*)::int n from public.vh_collection_assets where asset_id=$1`,[a])).rows[0]!.n).toBe(0); expect((await db.query<{n:number}>(`select count(*)::int n from public.vh_source_chunks where asset_id=$1`,[a])).rows[0]!.n).toBe(0); expect((await db.query<{n:number}>(`select count(*)::int n from public.vh_storage_objects where id=$1`,[storage])).rows[0]!.n).toBe(0)
    const keep=await asset(db,A,{hashSeed:'universal-keep',title:'Universal Keep'}), p2=await project(db,A,'Delete container'); await db.query(`select public.vh_add_project_reference($1,$2,$3)`,[A,p2,keep]); await db.query(`update public.vh_projects set trashed_at=now(),purge_after=now()+interval '30 days' where id=$1`,[p2]); expect((await db.query<{ok:boolean}>(`select public.vh_delete_part2_metadata($1,'project',$2) ok`,[A,p2])).rows[0]!.ok).toBe(true); expect((await db.query<{n:number}>(`select count(*)::int n from public.vh_library_assets where id=$1`,[keep])).rows[0]!.n).toBe(1); expect((await db.query<{ok:boolean}>(`select public.vh_delete_part2_metadata($1,'project',$2) ok`,[B,p])).rows[0]!.ok).toBe(false)
  })
})
